#!/usr/bin/env python3
"""
Part 2: Add contemporary pioneers (PION_200-PION_253).
Run from project root: python3 05_validation/add_trunk3_part2_con_pioneers.py
"""
import csv, json, os

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '04_nodes_edges')

def append_rows(fname, fieldnames, rows):
    path = os.path.join(BASE, fname)
    with open(path, 'a', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
        for r in rows:
            w.writerow(r)
    print(f"  + {fname}: {len(rows)} rows added")

def J(lst): return json.dumps(lst, ensure_ascii=False)

PION_FIELDS = ['pioneer_id','name','birth_year','death_year','nationality','primary_fields',
               'contributions_summary','key_ideas_json','representative_works_json',
               'fields_influenced','cross_trunk_impact','contemporaries','controversies',
               'source_ids','confidence','evidence_type']

con_pioneers = [
  # ── QFT / QED ──────────────────────────────────────────────────────────────
  {'pioneer_id':'PION_200','name':'Richard Feynman','birth_year':'1918','death_year':'1988',
   'nationality':'USA','primary_fields':'quantum electrodynamics, quantum field theory, quantum computing',
   'contributions_summary':'Co-developed QED renormalization (1946-1949) independently; invented Feynman diagrams — visual/calculational tool now universal across physics; parton model of nucleon structure; proposed quantum computer concept (1982); Feynman Lectures on Physics (1963); Nobel Physics 1965',
   'key_ideas_json':J(["QED path-integral formulation: sum over all possible paths of particle; alternative to Schwinger and Tomonaga operator methods","Feynman diagrams (1948): spacetime diagrams representing particle interactions; calculational tool adopted universally in quantum field theory","Parton model (1969): nucleons contain point-like constituents (partons/quarks) explaining deep inelastic scattering","Quantum computing concept (1982 lecture): quantum system to simulate quantum systems — computational power unavailable classically"]),
   'representative_works_json':J(["Space-Time Approach to Quantum Electrodynamics (1949, Physical Review 76)","The Feynman Lectures on Physics (1963, 3 vols)","QED: The Strange Theory of Light and Matter (1985)"]),
   'fields_influenced':'QFT, condensed matter, quantum computing, particle physics',
   'cross_trunk_impact':'Quantum computing (CON_011); condensed matter effective field theories; inspired entire generation of physicists',
   'contemporaries':'Julian Schwinger (independent QED), Sin-Itiro Tomonaga (independent QED), Freeman Dyson (unified three formulations)',
   'controversies':'Feynman diagrams initially resisted by Schwinger who considered them insufficiently rigorous; Feynman publicly criticized Manhattan Project security after-the-fact; personal behavior controversies documented posthumously',
   'source_ids':'SRC_099','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_201','name':'Julian Schwinger','birth_year':'1918','death_year':'1994',
   'nationality':'USA','primary_fields':'quantum electrodynamics, quantum field theory',
   'contributions_summary':'Independent QED formulation (1946-1949) using operator field theory methods; renormalization of QED; predicted and calculated anomalous magnetic moment of electron (1948); source theory (later career, unconventional); Nobel Physics 1965 shared with Feynman and Tomonaga; trained many Nobel laureates',
   'key_ideas_json':J(["QED operator method: rigorous mathematical treatment using Green functions and field operators","Anomalous magnetic moment: g-factor of electron differs from exactly 2; calculated QED correction α/2π — first precision QED prediction","Renormalization: systematic procedure for removing divergences in QED calculations","Source theory (1970s): alternative to conventional QFT; largely not adopted by community"]),
   'representative_works_json':J(["On Quantum-Electrodynamics and the Magnetic Moment of the Electron (1948, Physical Review 73)","Quantum Electrodynamics (collected papers, 1958)"]),
   'fields_influenced':'QFT, quantum electrodynamics, nuclear physics',
   'cross_trunk_impact':'Nuclear physics applications; precision electromagnetic measurements',
   'contemporaries':'Richard Feynman (independent QED), Sin-Itiro Tomonaga (independent QED), Freeman Dyson',
   'controversies':'Feynman-Schwinger rivalry; Schwinger method harder to use than Feynman diagrams, which dominated community; source theory criticized as not equivalent to standard QFT; teaching style demanding',
   'source_ids':'SRC_099','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_202','name':'Sin-Itirō Tomonaga','birth_year':'1906','death_year':'1979',
   'nationality':'Japan','primary_fields':'quantum electrodynamics, quantum field theory',
   'contributions_summary':'Independent QED formulation in wartime Japan (1943-1947, published 1946-1947); super-many-time theory — covariant treatment of quantum field theory; Nobel Physics 1965; demonstrated physics could progress independently under wartime isolation',
   'key_ideas_json':J(["Super-many-time theory (1943): Lorentz-covariant formulation of quantum field dynamics; each field point has its own time parameter","Renormalization independently discovered in Japan: QED divergences removable by mass and charge renormalization","Independent development: equivalent results to Feynman and Schwinger without direct communication during WWII"]),
   'representative_works_json':J(["On a Relativistically Invariant Formulation of the Quantum Theory of Wave Fields (1946, Progress of Theoretical Physics)","Scientific Papers of Tomonaga (2 vols, 1971)"]),
   'fields_influenced':'QFT, theoretical physics in Japan',
   'cross_trunk_impact':'Established Japanese physics community; demonstrated non-Western independent contributions to highest-level theoretical physics',
   'contemporaries':'Richard Feynman (independent QED), Julian Schwinger (independent QED), Freeman Dyson',
   'controversies':'Work initially unknown in West due to language and wartime isolation; Dyson-mediated recognition was critical for Nobel consideration',
   'source_ids':'SRC_099','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_203','name':'Freeman Dyson','birth_year':'1923','death_year':'2020',
   'nationality':'UK/USA','primary_fields':'quantum electrodynamics, mathematical physics',
   'contributions_summary':'Proved mathematical equivalence of Feynman, Schwinger, and Tomonaga QED formulations (1948-1949) — unified quantum field theory; Dyson-Schwinger equations; wide contributions including solid state physics, nuclear weapons design (Project Orion), SETI; never received Nobel (widely considered oversight)',
   'key_ideas_json':J(["QED unification (1948-1949): proved Feynman path-integral, Schwinger operator, and Tomonaga covariant methods are mathematically equivalent","Renormalization proof: showed all divergences in QED are removable to all orders of perturbation theory","Dyson-Schwinger equations: non-perturbative integral equations for quantum field propagators and vertices"]),
   'representative_works_json':J(["The Radiation Theories of Tomonaga, Schwinger, and Feynman (1949, Physical Review 75)","The S-Matrix in Quantum Electrodynamics (1949, Physical Review 75)"]),
   'fields_influenced':'QFT, mathematical physics, nuclear physics, astrophysics',
   'cross_trunk_impact':'Wide influence across physics; science writing reached general public; Project Orion (nuclear propulsion)',
   'contemporaries':'Richard Feynman (Princeton/Cornell), Julian Schwinger, Sin-Itiro Tomonaga; Robert Oppenheimer (IAS director)',
   'controversies':'Never received Nobel Prize despite unifying QED — attributed to Nobelitis (Nobel committee does not award for unification, only discovery); later career heretical views on climate modeling; unconventional positions on multiple topics',
   'source_ids':'SRC_099','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_204','name':'Murray Gell-Mann','birth_year':'1929','death_year':'2019',
   'nationality':'USA','primary_fields':'particle physics, quantum field theory',
   'contributions_summary':'Quark model (1964) — quarks as fundamental constituents of hadrons (up, down, strange quarks); strangeness quantum number (1953); eightfold way (1961) organizing hadrons by SU(3) symmetry; QCD co-development; coined term "quark" from Finnegans Wake; Nobel Physics 1969',
   'key_ideas_json':J(["Quark model (1964, independently with Zweig): hadrons are composed of fractionally charged quarks u, d, s; explains hadron spectrum","Strangeness (1953): new quantum number conserved in strong interactions, not weak — explains K-meson behavior","Eightfold way (1961): SU(3) symmetry classifies baryons and mesons in octets and decuplets","QCD development: with Fritzsch (1972) proposed color charge and gluon exchange as strong force mechanism"]),
   'representative_works_json':J(["Isotopic Spin and New Unstable Particles (1953, Physical Review 92)","A Schematic Model of Baryons and Mesons (1964, Physics Letters 8)"]),
   'fields_influenced':'particle physics, quantum field theory, Standard Model',
   'cross_trunk_impact':'Particle physics extended knowledge of fundamental constituents of all matter; QCD as part of Standard Model',
   'contemporaries':'Richard Feynman (Caltech colleague, rival), George Zweig (independent quark model), Steven Weinberg, Sheldon Glashow',
   'controversies':'Priority dispute with George Zweig over quark model (Zweig called them aces independently); Feynman and Gell-Mann had famous productive rivalry/tension; complexity theory interests late career seen as departure',
   'source_ids':'SRC_100','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_205','name':'Steven Weinberg','birth_year':'1933','death_year':'2021',
   'nationality':'USA','primary_fields':'quantum field theory, electroweak theory, cosmology',
   'contributions_summary':'Electroweak unification (1967) — unified electromagnetic and weak nuclear forces as aspects of single electroweak force; Weinberg-Salam model predicted W and Z bosons (confirmed 1983); The Quantum Theory of Fields (1995) definitive textbook; The First Three Minutes (1977) cosmology popularization; Nobel Physics 1979',
   'key_ideas_json':J(["Electroweak unification (1967): electromagnetic and weak forces unified at energies above ~100 GeV; described by SU(2)×U(1) gauge theory","W and Z boson prediction: massive gauge bosons carry weak force; masses predicted from electroweak theory, confirmed at CERN 1983","Spontaneous symmetry breaking: Higgs mechanism gives W and Z bosons masses while photon remains massless","Effective field theory: framework for understanding low-energy limits of underlying theories"]),
   'representative_works_json':J(["A Model of Leptons (1967, Physical Review Letters 19)","The Quantum Theory of Fields (3 vols, 1995-2000)"]),
   'fields_influenced':'particle physics, quantum field theory, cosmology, Standard Model',
   'cross_trunk_impact':'Standard Model cornerstone; effective field theory used across condensed matter; cosmology connection through Big Bang nucleosynthesis',
   'contemporaries':'Sheldon Glashow (collaborator/rival), Abdus Salam (independent electroweak), Murray Gell-Mann',
   'controversies':'Weinberg-Glashow-Salam model initially ignored (1967-1971) until t Hooft proved renormalizability; tensions with particle physics community over interpretation questions',
   'source_ids':'SRC_100','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_206','name':'David Gross','birth_year':'1941','death_year':None,
   'nationality':'USA','primary_fields':'quantum chromodynamics, quantum field theory',
   'contributions_summary':'Asymptotic freedom in QCD (1973, with Politzer and Wilczek) — quarks interact weakly at high energies but strongly at low energies; made QCD a calculable theory; explains quark confinement; Nobel Physics 2004',
   'key_ideas_json':J(["Asymptotic freedom (1973): QCD coupling constant decreases at high energy (short distances) — quarks are nearly free at very high energy","Non-Abelian gauge theory renormalization: first computed one-loop beta function for SU(3) gauge theory, finding it negative","Implications: explains why perturbation theory works for high-energy scattering; explains Bjorken scaling in deep inelastic scattering"]),
   'representative_works_json':J(["Ultraviolet Behavior of Non-Abelian Gauge Theories (1973, Physical Review Letters, with Wilczek)","The Discovery of Asymptotic Freedom and the Emergence of QCD (Nobel lecture 2004)"]),
   'fields_influenced':'QCD, particle physics, Standard Model, string theory',
   'cross_trunk_impact':'QCD as component of Standard Model; string theory research (KITP, Santa Barbara)',
   'contemporaries':'Frank Wilczek (collaborator), David Politzer (independent discovery), Steven Weinberg, Edward Witten',
   'controversies':'Simultaneous discovery with Politzer (Harvard) caused priority dispute; Gross and Wilczek at Princeton, Politzer at Harvard published simultaneously; Nobel shared three ways',
   'source_ids':'SRC_100','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_207','name':'Peter Higgs','birth_year':'1929','death_year':'2024',
   'nationality':'UK','primary_fields':'quantum field theory, particle physics',
   'contributions_summary':'Higgs mechanism (1964) — explains how elementary particles acquire mass through interaction with the Higgs field; Higgs boson predicted as quantum of the field; boson confirmed at CERN LHC (2012); Nobel Physics 2013 shared with François Englert',
   'key_ideas_json':J(["Higgs mechanism (1964): spontaneous symmetry breaking of electroweak gauge symmetry; W and Z bosons acquire mass by interacting with Higgs field","Higgs boson: scalar particle predicted as excitation of Higgs field; mass predicted ~125 GeV, confirmed 2012","Mass generation: without Higgs field, all elementary particles would be massless; mechanism unified with electroweak theory"]),
   'representative_works_json':J(["Broken Symmetries and the Masses of Gauge Bosons (1964, Physical Review Letters 13)","Broken Symmetries, Massless Particles and Gauge Fields (1964, Physics Letters)"]),
   'fields_influenced':'particle physics, Standard Model, electroweak theory',
   'cross_trunk_impact':'Standard Model completion; LHC experimental physics; fundamental understanding of mass',
   'contemporaries':'François Englert (independent mechanism), Robert Brout, Philip Anderson (related mechanism in superconductivity)',
   'controversies':'Englert-Brout paper published slightly before Higgs; Anderson had similar idea in condensed matter context (1962); particle became known as Higgs boson over objection of others who contributed',
   'source_ids':'SRC_100','confidence':'A','evidence_type':'E2'},

  # ── CONDENSED MATTER PHYSICS ───────────────────────────────────────────────
  {'pioneer_id':'PION_208','name':'John Bardeen','birth_year':'1908','death_year':'1991',
   'nationality':'USA','primary_fields':'condensed matter physics, semiconductor physics, superconductivity',
   'contributions_summary':'Transistor invention (1947, Bell Labs, with Brattain and Shockley) — Nobel Physics 1956; BCS theory of superconductivity (1957, with Cooper and Schrieffer) — Nobel Physics 1972; only person in history to win Nobel Prize in Physics twice; Bell Labs and UIUC career',
   'key_ideas_json':J(["Transistor (1947): semiconductor device amplifying electrical signals using p-n junction — point contact then junction type; replaced vacuum tubes","BCS theory (1957): superconductivity explained by phonon-mediated Cooper pairing; collective quantum state of all Cooper pairs; predicts coherence length, specific heat, isotope effect","Surface state theory: understood role of surface states in semiconductor behavior — led to transistor concept"]),
   'representative_works_json':J(["The Transistor, A Semi-Conductor Triode (1948, Physical Review, with Brattain)","Theory of Superconductivity (1957, Physical Review 108, with Cooper and Schrieffer)"]),
   'fields_influenced':'condensed matter, semiconductor physics, superconductivity, computing technology',
   'cross_trunk_impact':'Computing civilization enabled by transistor (Trunk 9 / Computer Science); semiconductor industry (Trunk 8)',
   'contemporaries':'Walter Brattain (transistor co-inventor), William Shockley (transistor co-inventor), Leon Cooper and John Robert Schrieffer (BCS)',
   'controversies':'Shockley took credit for transistor from Bardeen and Brattain; BCS publication had complex priority negotiations; Bardeen left Bell Labs partly due to Shockley tensions',
   'source_ids':'SRC_091, SRC_093','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_209','name':'William Shockley','birth_year':'1910','death_year':'1989',
   'nationality':'USA','primary_fields':'semiconductor physics, solid state physics',
   'contributions_summary':'Transistor co-inventor (Nobel Physics 1956); junction transistor design (1949); founding of Shockley Semiconductor Laboratory (1955) — spawned Silicon Valley; Electrons and Holes in Semiconductors textbook (1950); later controversial racial science advocacy',
   'key_ideas_json':J(["Junction transistor (1949): improved transistor design using p-n-p or n-p-n sandwich; more reliable than point contact; became standard form","Semiconductor theory: developed rigorous theory of electrons and holes in semiconductors; minority carrier injection","Silicon Valley founding: left Bell Labs; recruited exceptional engineers; traitors eight left to found Fairchild; Fairchild to Intel chain"]),
   'representative_works_json':J(["Electrons and Holes in Semiconductors (1950, Van Nostrand)","The Theory of p-n Junctions in Semiconductors (1949, Bell System Technical Journal)"]),
   'fields_influenced':'semiconductor physics, solid state physics, Silicon Valley ecosystem',
   'cross_trunk_impact':'Silicon Valley ecosystem (Trunk 8/engineering); modern computing hardware',
   'contemporaries':'John Bardeen (transistor), Walter Brattain (transistor), Gordon Moore (Fairchild/Intel)',
   'controversies':'Took credit from Bardeen and Brattain; fired or alienated his talented semiconductor team (the traitorous eight); later became advocate for racial intelligence theories, destroying his scientific reputation',
   'source_ids':'SRC_093','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_210','name':'Philip Anderson','birth_year':'1923','death_year':'2020',
   'nationality':'USA','primary_fields':'condensed matter physics, solid state physics',
   'contributions_summary':'Anderson localization (1958) — electrons in disordered lattice can become localized; More is Different (1972) — emergence principle foundational to condensed matter; antiferromagnetism theory; superexchange mechanism; helped transform solid state to condensed matter physics; Bell Labs and Princeton; Nobel Physics 1977',
   'key_ideas_json':J(["Anderson localization (1958): electrons in sufficiently disordered lattice become localized (non-conducting) — important for amorphous semiconductors","More is Different (1972): emergent properties at each level of complexity not reducible to lower-level physics — philosophical manifesto of CMP","Superexchange: magnetic interaction mechanism between non-nearest-neighbor ions through intermediate atoms","Anderson-Higgs mechanism: Anderson's 1963 condensed matter paper anticipated Higgs mechanism for mass generation"]),
   'representative_works_json':J(["Absence of Diffusion in Certain Random Lattices (1958, Physical Review 109)","More is Different (1972, Science 177)"]),
   'fields_influenced':'condensed matter, disorder physics, high-Tc superconductivity (active contributor), emergence theory',
   'cross_trunk_impact':'Philosophy of science via emergence principle; resonance finance/economics (emergence in complex systems)',
   'contemporaries':'Nevill Mott (Nobel shared 1977), John van Vleck (Nobel shared), John Bardeen (Bell Labs)',
   'controversies':'Controversial proposal for RVB (resonating valence bond) theory of high-Tc superconductivity (1987) — championed but disputed; strong views on theoretical physics agenda',
   'source_ids':'SRC_091, SRC_093','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_211','name':'Nevill Mott','birth_year':'1905','death_year':'1996',
   'nationality':'UK','primary_fields':'condensed matter physics, semiconductor physics',
   'contributions_summary':'Mott insulators — metal-insulator transition in transition metal oxides explained by electron correlation (Mott transition); theory of amorphous semiconductors; photographic emulsion theory (silver halide); Nobel Physics 1977 with Anderson and van Vleck',
   'key_ideas_json':J(["Mott insulator (1949): materials that should be metallic by band theory but are insulating due to electron-electron repulsion (correlation); Mott-Hubbard model","Metal-insulator (Mott) transition: parameter-driven transition from metallic to insulating state","Amorphous semiconductors: electronic properties of non-crystalline materials — basis for amorphous silicon solar cells"]),
   'representative_works_json':J(["The Basis of the Electron Theory of Metals, with Special Reference to the Transition Metals (Nobel lecture 1977)","Electronic Processes in Non-Crystalline Materials (1971, with E.A. Davis)"]),
   'fields_influenced':'condensed matter, correlated electron systems, disordered systems, high-Tc research',
   'cross_trunk_impact':'Strongly correlated electron systems remain active frontier; Mott insulator concept central to high-Tc mechanism debate',
   'contemporaries':'Philip Anderson (Nobel shared), Rudolf Peierls (UK physics), John Slater',
   'controversies':'Mott transition mechanism competed with band theory explanations; high-Tc debate connections',
   'source_ids':'SRC_090, SRC_091','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_212','name':'Leon Cooper','birth_year':'1930','death_year':None,
   'nationality':'USA','primary_fields':'condensed matter physics, superconductivity',
   'contributions_summary':'Cooper pairs (1956) — phonon-mediated pairing of electrons with opposite momenta and spins in superconductors; BCS theory co-author (1957, with Bardeen and Schrieffer); Nobel Physics 1972; Brown University career',
   'key_ideas_json':J(["Cooper pairs (1956): two electrons near the Fermi surface form bound pair via phonon-mediated attraction, despite Coulomb repulsion; pairs have opposite momenta and spins","BCS Cooper pair condensate: all Cooper pairs condense into single macroscopic quantum state — explains zero resistance, Meissner effect","Cooper pair coherence length: quantum coherence extends over macroscopic distances in superconductors"]),
   'representative_works_json':J(["Bound Electron Pairs in a Degenerate Fermi Gas (1956, Physical Review 104)","Theory of Superconductivity (1957, Physical Review 108, BCS paper)"]),
   'fields_influenced':'superconductivity, condensed matter, quantum many-body theory',
   'cross_trunk_impact':'BCS pairing mechanism applied to nuclear physics (Cooper pairing in nuclei); Cooper pair concept in ultracold Fermi gases',
   'contemporaries':'John Bardeen (BCS), John Robert Schrieffer (BCS), Vitaly Ginzburg',
   'controversies':'Pre-BCS papers on Cooper pairing were not immediately recognized as key insight; role in BCS relative to Bardeen and Schrieffer debated in historical accounts',
   'source_ids':'SRC_091','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_213','name':'Brian Josephson','birth_year':'1940','death_year':None,
   'nationality':'UK','primary_fields':'condensed matter physics, superconductivity',
   'contributions_summary':'Josephson effect (1962) predicted as Cambridge PhD student: supercurrent tunnels through insulating barrier between two superconductors; DC Josephson effect (steady current); AC Josephson effect (oscillating current with applied voltage); Nobel Physics 1973; Josephson junctions now used in SQUIDs, superconducting qubits, and voltage standards',
   'key_ideas_json':J(["DC Josephson effect: Cooper pairs tunnel through thin insulating barrier between superconductors with no applied voltage","AC Josephson effect: applying voltage V across junction produces oscillating current at frequency 2eV/h — precise frequency-voltage relation","SQUID (Superconducting Quantum Interference Device): two Josephson junctions in loop; most sensitive magnetic field detector","Superconducting qubits: transmon and other qubits based on Josephson junction nonlinearity"]),
   'representative_works_json':J(["Possible New Effects in Superconductive Tunnelling (1962, Physics Letters 1)","The Discovery of Tunnelling Supercurrents (Nobel lecture 1973)"]),
   'fields_influenced':'superconductivity, quantum computing, precision measurement, metrology',
   'cross_trunk_impact':'Quantum computing hardware via superconducting qubits (CON_011); voltage standard in metrology; SQUID in medical imaging (MEG)',
   'contemporaries':'Philip Anderson (who independently predicted the effect), John Bardeen (who disputed Josephson), Brian Pippard (Cambridge supervisor)',
   'controversies':'Bardeen initially argued Josephson effect was impossible; Josephson correct against Nobel laureate; later career interests in consciousness and mind led to marginalization by physics community',
   'source_ids':'SRC_091','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_214','name':'Klaus von Klitzing','birth_year':'1943','death_year':None,
   'nationality':'Germany','primary_fields':'condensed matter physics, quantum Hall physics',
   'contributions_summary':'Discovered quantum Hall effect (1980) — Hall resistance in 2D electron system in strong magnetic field quantized to h/e² divided by integer, independent of sample geometry; Nobel Physics 1985; defines SI resistance standard (von Klitzing constant RK = 25812.807 Ω)',
   'key_ideas_json':J(["Integer quantum Hall effect (1980): Hall resistance quantized precisely to RK/n (n integer); independent of sample purity and geometry","Von Klitzing constant: h/e² = 25812.807 Ω — now defines resistance standard; related to fine structure constant","Topological origin: QHE is topological phenomenon — Thouless TKNN invariant; robust against disorder","Precursor to topological insulators: QHE edge states are topologically protected conducting channels"]),
   'representative_works_json':J(["New Method for High-Accuracy Determination of the Fine-Structure Constant Based on Quantized Hall Resistance (1980, Physical Review Letters 45)","Nobel lecture (1985)"]),
   'fields_influenced':'condensed matter, topological physics, metrology, precision measurement',
   'cross_trunk_impact':'SI units redefinition (2019) based on Josephson and von Klitzing constants; topological insulator research enabled',
   'contemporaries':'Horst Störmer and Daniel Tsui (fractional QHE 1982), Robert Laughlin (FQHE theory), Philip Anderson',
   'controversies':'Discovery initially doubted by some referees; publication in Physical Review Letters vs more established journals; rapid Nobel (5 years)',
   'source_ids':'SRC_093','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_215','name':'Johannes Georg Bednorz','birth_year':'1950','death_year':None,
   'nationality':'Germany','primary_fields':'condensed matter physics, superconductivity, materials science',
   'contributions_summary':'High-temperature superconductivity in cuprate ceramics (1986, with Müller) — La-Ba-Cu-O ceramic superconducts at 30 K, well above previous record; Nobel Physics 1987 (19 months after discovery — fastest Nobel ever awarded)',
   'key_ideas_json':J(["High-Tc superconductors (1986): cuprate ceramics with perovskite structure superconduct above 30K — later pushed above liquid nitrogen boiling point (77K)","Ceramic superconductors: surprising that ionic ceramic material could be superconducting; challenged BCS paradigm","Opened high-Tc research field: hundreds of groups worldwide competed to find higher transition temperatures after 1986"]),
   'representative_works_json':J(["Possible High Tc Superconductivity in the Ba-La-Cu-O System (1986, Zeitschrift für Physik B 64)"]),
   'fields_influenced':'superconductivity, condensed matter, materials science',
   'cross_trunk_impact':'Potential for room-temperature superconductivity (power transmission, maglev) — not yet achieved; ongoing research',
   'contemporaries':'K. Alex Müller (co-discoverer), Paul Chu (pushed to 90K with YBCO), Philip Anderson (RVB theory)',
   'controversies':'Mechanism of high-Tc superconductivity still unresolved 40+ years after discovery; competing theoretical proposals remain unresolved',
   'source_ids':'SRC_091','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_216','name':'K. Alex Müller','birth_year':'1927','death_year':'2023',
   'nationality':'Switzerland','primary_fields':'condensed matter physics, superconductivity',
   'contributions_summary':'High-temperature superconductivity in cuprate ceramics (1986, with Bednorz) — Nobel Physics 1987; studied Jahn-Teller effect and perovskite oxides for two years before discovery; IBM Zurich Research Laboratory career',
   'key_ideas_json':J(["Strategy: studied Jahn-Teller distorted perovskite oxides systematically as candidates for high-Tc — insight that electron-phonon coupling enhanced by Jahn-Teller effect","Cuprate perovskites: La2CuO4 doped with Ba or Sr shows high-Tc superconductivity","IBM Zurich collaboration: Müller and Bednorz worked quietly for two years before announcement"]),
   'representative_works_json':J(["Possible High Tc Superconductivity in the Ba-La-Cu-O System (1986, Zeitschrift für Physik B, with Bednorz)"]),
   'fields_influenced':'superconductivity, condensed matter, materials science, perovskite oxides',
   'cross_trunk_impact':'Perovskite oxides research (also relevant to ferroelectrics, multiferroics)',
   'contemporaries':'Johannes Georg Bednorz (co-discoverer), Ted Geballe, Robert Cava',
   'controversies':'High-Tc mechanism debate: Müller favored polaronic mechanism while most community believes d-wave pairing; debate unresolved',
   'source_ids':'SRC_091','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_217','name':'Andre Geim','birth_year':'1958','death_year':None,
   'nationality':'Netherlands/UK','primary_fields':'condensed matter physics, nanotechnology',
   'contributions_summary':'Isolated graphene (2004, with Novoselov) using scotch tape mechanical exfoliation; characterized 2D Dirac fermion properties; Nobel Physics 2010; also known for Ig Nobel award (levitating frog with magnets); Manchester University',
   'key_ideas_json':J(["Graphene isolation (2004): single atomic layer of carbon in honeycomb lattice isolated by simple tape method from graphite","Dirac fermions in graphene: electrons in graphene behave as massless relativistic particles; anomalous quantum Hall effect","Scotch tape method: deceptively simple mechanical exfoliation; key insight that single layers could be transferred and studied","2D materials paradigm: graphene opened exploration of MoS2, hBN, and other 2D materials"]),
   'representative_works_json':J(["Electric Field Effect in Atomically Thin Carbon Films (2004, Science, with Novoselov)"]),
   'fields_influenced':'condensed matter, 2D materials, nanotechnology, materials science',
   'cross_trunk_impact':'Nanotechnology applications (CON_006, CON_010); semiconductor electronics at 2D limit',
   'contemporaries':'Konstantin Novoselov (co-discoverer), Philip Kim (independent graphene work), Walt de Heer',
   'controversies':'Priority: several groups approaching graphene independently; scotch tape method elegance vs earlier chemical vapor deposition approaches; Geim somewhat unconventional career (Ig Nobel, Flying Frog)',
   'source_ids':'SRC_095','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_218','name':'Konstantin Novoselov','birth_year':'1974','death_year':None,
   'nationality':'Russia/UK','primary_fields':'condensed matter physics, 2D materials',
   'contributions_summary':'Graphene isolation and characterization (2004, with Geim) — Nobel Physics 2010; characterization of quantum Hall effect in graphene; 2D material heterostructure research; youngest Nobel laureate in physics at that time (36)',
   'key_ideas_json':J(["Graphene quantum Hall effect: anomalous QHE at room temperature in graphene; Berry phase effect","van der Waals heterostructures: stacking different 2D materials to engineer properties — boron nitride encapsulation of graphene","2D material zoo: systematic exploration of MoS2 and other transition metal dichalcogenides as 2D semiconductors"]),
   'representative_works_json':J(["Electric Field Effect in Atomically Thin Carbon Films (2004, Science)","Two-dimensional gas of massless Dirac fermions in graphene (2005, Nature)"]),
   'fields_influenced':'2D materials, condensed matter, nanotechnology, quantum Hall physics',
   'cross_trunk_impact':'2D materials for electronics, sensors, photonics',
   'contemporaries':'Andre Geim (co-discoverer and PhD supervisor), Philip Kim, Pablo Jarillo-Herrero (magic-angle graphene 2018)',
   'controversies':'Youngest Physics Nobel laureate controversy; magic-angle graphene (twisted bilayer, 2018) extended his work dramatically',
   'source_ids':'SRC_095','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_219','name':'David Thouless','birth_year':'1934','death_year':'2019',
   'nationality':'UK/USA','primary_fields':'condensed matter physics, topological physics',
   'contributions_summary':'TKNN invariant (1982, with Kohmoto, Nightingale, den Nijs) — topological origin of quantized Hall conductance; Kosterlitz-Thouless phase transition (1972-1973, with Kosterlitz) — topological defects driving phase transition in 2D systems; Nobel Physics 2016',
   'key_ideas_json':J(["TKNN invariant (1982): Hall conductance of QHE given by topological invariant (Chern number) of occupied bands — explains exactness of quantization","Kosterlitz-Thouless transition (1972-1973): 2D systems undergo phase transition via unbinding of topological vortex pairs, not conventional symmetry breaking","Topological band theory: topology classifies distinct phases of matter; topological insulators emerged from this framework"]),
   'representative_works_json':J(["Ordering, Metastability and Phase Transitions in Two-Dimensional Systems (1973, Journal of Physics C, with Kosterlitz)","Quantized Hall Conductance in a Two-Dimensional Periodic Potential (1982, Physical Review Letters, TKNN)"]),
   'fields_influenced':'condensed matter, topological physics, topological insulators, quantum computing',
   'cross_trunk_impact':'Topological quantum computing via non-Abelian anyons in topological materials',
   'contemporaries':'J. Michael Kosterlitz (Nobel shared), Duncan Haldane (Nobel shared), Philip Anderson',
   'controversies':'Topological insulators experimental realization came 30+ years after theoretical prediction',
   'source_ids':'SRC_093','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_220','name':'Duncan Haldane','birth_year':'1951','death_year':None,
   'nationality':'UK/USA','primary_fields':'condensed matter physics, topological physics',
   'contributions_summary':'Haldane chain (1983) — integer-spin antiferromagnetic chains have gap while half-integer spin chains are gapless; topological classification of phases; fractional quantum Hall edge states theory; Berry phase in condensed matter; Nobel Physics 2016',
   'key_ideas_json':J(["Haldane chain (1983): 1D integer-spin antiferromagnet has energy gap (Haldane gap); half-integer spin chains are gapless — unexpected difference","Haldane model (1988): 2D lattice model with broken time-reversal symmetry; first model of quantum anomalous Hall effect — precursor to topological insulators","Berry phase in condensed matter: geometric phase affecting quantum system carried around loop in parameter space"]),
   'representative_works_json':J(["Nonlinear Field Theory of Large-Spin Heisenberg Antiferromagnets (1983, Physical Review Letters 50)","Model for a Quantum Hall Effect without Landau Levels (1988, Physical Review Letters 61)"]),
   'fields_influenced':'condensed matter, topological phases, quantum magnetism, quantum computing',
   'cross_trunk_impact':'Topological quantum computing; quantum magnetism; topological insulator materials',
   'contemporaries':'David Thouless (Nobel shared), J. Michael Kosterlitz (Nobel shared), Frank Haldane (no relation)',
   'controversies':'Haldane gap prediction initially controversial; Haldane model (1988) largely ignored for 15 years until topological insulator experiments confirmed its implications',
   'source_ids':'SRC_093','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_221','name':'J. Michael Kosterlitz','birth_year':'1943','death_year':None,
   'nationality':'UK/USA','primary_fields':'condensed matter physics, topological phase transitions',
   'contributions_summary':'Kosterlitz-Thouless (KT) phase transition (1972-1973, with Thouless) — in 2D systems, phase transition driven by binding and unbinding of topological vortex pairs; applicable to 2D magnets, superfluid helium films, superconducting films; Nobel Physics 2016',
   'key_ideas_json':J(["KT transition: 2D systems cannot have conventional long-range order (Mermin-Wagner) but can have topological phase transition at finite temperature","Vortex unbinding: below T_KT, vortex-antivortex pairs bound; above T_KT, free vortices proliferate, destroying quasi-long-range order","Universal jump in superfluid density: superfluid helium films show universal jump at T_KT — confirmed experimentally"]),
   'representative_works_json':J(["Ordering, Metastability and Phase Transitions in Two-Dimensional Systems (1973, Journal of Physics C, with Thouless)"]),
   'fields_influenced':'condensed matter, phase transition theory, superfluidity, 2D physics',
   'cross_trunk_impact':'KT transition in 2D superconductors; 2D magnetic films; atomic physics (cold atom BEC in 2D)',
   'contemporaries':'David Thouless (Nobel shared), Duncan Haldane (Nobel shared), Bertrand Halperin',
   'controversies':'KT transition theoretical prediction; experimental confirmation required decades; Nobel awarded 43 years after original paper',
   'source_ids':'SRC_093','confidence':'A','evidence_type':'E2'},

  # ── MATERIALS SCIENCE ──────────────────────────────────────────────────────
  {'pioneer_id':'PION_222','name':'Morris Cohen','birth_year':'1911','death_year':'2005',
   'nationality':'USA','primary_fields':'materials science, metallurgy',
   'contributions_summary':'Pioneer of Materials Science as academic discipline at MIT; led transformation of MIT metallurgy department into materials science; martensitic transformation research; influential in ARPA IDL programs 1960s; defined "materials tetrahedron" pedagogical framework (structure-properties-processing-performance)',
   'key_ideas_json':J(["Materials science institutionalization: led MIT Department of Metallurgy transformation to Materials Science; influenced ARPA IDL program structure","Materials tetrahedron: structure ↔ properties ↔ processing ↔ performance as organizing pedagogical framework for materials science","Martensite research: diffusionless phase transformation in steel; crystallographic theory of martensitic transformation"]),
   'representative_works_json':J(["MIT Department of Materials Science inaugural curriculum (1960s)","Martensitic transformations research (multiple papers, MIT)"]),
   'fields_influenced':'materials science, metallurgy, materials engineering education',
   'cross_trunk_impact':'Industrial metallurgy and materials engineering (Trunk 8); defined academic discipline structure',
   'contemporaries':'Cyril Stanley Smith (MIT colleague), John Wulff (MIT), Bever (MIT history)',
   'controversies':'Credit for founding materials science contested among MIT, Cornell, and other ARPA IDL universities',
   'source_ids':'SRC_101','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_223','name':'Cyril Stanley Smith','birth_year':'1903','death_year':'1992',
   'nationality':'UK/USA','primary_fields':'metallurgy, history of materials science',
   'contributions_summary':'Metallurgist and historian of materials; grain boundary and microstructure theory; Manhattan Project materials director (Los Alamos); historian of metallurgy tracing from ancient times; bridged Trunk 3 (science) and Trunk 8 (practical arts) in materials knowledge',
   'key_ideas_json':J(["Grain boundary theory: physical and chemical properties of grain boundaries in metals; grain growth kinetics","History of metallurgy: documented continuity from ancient metallurgy to modern materials science — Trunk 3-Trunk 8 bridge","Manhattan Project: directed materials research at Los Alamos; plutonium metallurgy for implosion device"]),
   'representative_works_json':J(["A History of Metallography (1960, University of Chicago Press)","From Art to Science: Seventy-Two Objects Illustrating the Nature of Discovery (1980)"]),
   'fields_influenced':'metallurgy, materials science, history of science, ancient technology',
   'cross_trunk_impact':'History of technology (Trunk 8); Manhattan Project (nuclear physics, Trunk 3); ancient crafts to science connection',
   'contemporaries':'Morris Cohen (MIT colleague), Robert Cahn (materials science history), Buerger (crystallography)',
   'controversies':'Manhattan Project involvement; historical methodology in science history debated',
   'source_ids':'SRC_094','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_224','name':'Paul Flory','birth_year':'1910','death_year':'1985',
   'nationality':'USA','primary_fields':'polymer science, physical chemistry',
   'contributions_summary':'Polymer chain statistics and thermodynamics; Flory-Huggins theory of polymer solutions (1941-1942); Flory exponent for polymer chain scaling; excluded volume theory; Nobel Chemistry 1974; Stanford professor',
   'key_ideas_json':J(["Flory-Huggins theory (1941-1942): thermodynamics of polymer-solvent mixtures; Flory-Huggins parameter χ quantifies solvent quality","Flory exponent: polymer chain size scales as N^ν where ν≈0.588 in good solvent (Flory exponent) due to excluded volume","Rotational isomeric state model: chain conformations modeled as rotational states about backbone bonds","Random coil model: polymer chain in theta solvent behaves as random walk"]),
   'representative_works_json':J(["Principles of Polymer Chemistry (1953, Cornell University Press)","Statistical Mechanics of Chain Molecules (1969)"]),
   'fields_influenced':'polymer science, soft matter, biopolymers, colloidal science',
   'cross_trunk_impact':'Biopolymers (Trunk 5 — protein chain statistics); rubber physics and technology (Trunk 8)',
   'contemporaries':'Paul Debye (polymer X-ray scattering), Bruno Zimm (light scattering theory), Pierre-Gilles de Gennes (scaling theory extended his work)',
   'controversies':'Flory exponent: Flory 0.6 approximation replaced by exact de Gennes renormalization group treatment; debate over chain statistics in polymer melts',
   'source_ids':'SRC_094','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_225','name':'Pierre-Gilles de Gennes','birth_year':'1932','death_year':'2007',
   'nationality':'France','primary_fields':'polymer science, soft matter physics, liquid crystals',
   'contributions_summary':'Scaling theory for polymers (extending Flory); liquid crystal theory; wetting and adhesion physics; soft matter physics as intellectual field identity; Nobel Physics 1991',
   'key_ideas_json':J(["Scaling theory for polymers: renormalization group applied to polymer conformations; exact Flory exponent calculation","Liquid crystal theory: order parameter for nematic and smectic phases; defect topology in liquid crystals","Soft matter physics: unified conceptual framework for polymers, colloids, liquid crystals, gels, foams — all share slow dynamics and sensitivity to weak forces","Reptation model: polymer chain in entangled melt moves by snake-like reptation along its own contour"]),
   'representative_works_json':J(["Scaling Concepts in Polymer Physics (1979, Cornell University Press)","The Physics of Liquid Crystals (1974)"]),
   'fields_influenced':'polymer physics, soft matter, liquid crystals, biological materials, colloids',
   'cross_trunk_impact':'Liquid crystal displays (Trunk 8 technology); biophysics of polymers (Trunk 5)',
   'contemporaries':'Paul Flory (precursor), Samuel Edwards (polymer theory), Sam Safran (soft matter)',
   'controversies':'Reptation model controversial vs other chain dynamics models; Nobel acknowledged as unusual for a physicist working in chemistry-adjacent areas',
   'source_ids':'SRC_092','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_226','name':'Herbert Kroemer','birth_year':'1928','death_year':'2024',
   'nationality':'Germany/USA','primary_fields':'semiconductor physics, heterostructures',
   'contributions_summary':'Double heterostructure laser and LED concept (1963) — semiconductor laser based on heterojunction; quasi-electric fields in heterostructures; Nobel Physics 2000 shared with Alferov and Kilby; UC Santa Barbara',
   'key_ideas_json':J(["Double heterostructure (1963): semiconductor laser using thin active layer sandwiched between wider-bandgap cladding layers — enables carrier and photon confinement; practical semiconductor laser","Quasi-electric fields: band discontinuities at heterointerface act as effective electric fields on carriers","Heterostructure principle: by varying bandgap spatially, carrier and photon behavior can be engineered — semiconductor band engineering"]),
   'representative_works_json':J(["A Proposed Class of Hetero-Junction Injection Lasers (1963, Proceedings of the IEEE)","Nobel lecture (2000): Quasi-Electric Fields and Band Offsets"]),
   'fields_influenced':'semiconductor physics, photonics, optoelectronics, solar cells',
   'cross_trunk_impact':'Semiconductor lasers (fiber optics communications, Trunk 8); LED technology (lighting); solar cells',
   'contemporaries':'Zhores Alferov (independent heterostructure), Jack Kilby (IC Nobel shared), Robert Noyce (IC)',
   'controversies':'Kroemer and Alferov independently proposed and demonstrated heterostructure lasers; Russian-American priority contest during Cold War',
   'source_ids':'SRC_094','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_227','name':'Zhores Alferov','birth_year':'1930','death_year':'2019',
   'nationality':'Russia/USSR','primary_fields':'semiconductor physics, heterostructures',
   'contributions_summary':'Independent development and practical demonstration of double heterostructure semiconductor lasers and LEDs in USSR (1960s); first continuous-wave semiconductor laser at room temperature; Nobel Physics 2000 shared with Kroemer and Kilby; Ioffe Institute, Leningrad',
   'key_ideas_json':J(["Double heterostructure demonstration: first practical room-temperature continuous-wave semiconductor laser (1970) — simultaneous with Hayashi at Bell Labs","AlGaAs/GaAs system: developed high-quality III-V semiconductor heterostructures in Soviet system with limited resources","Applications: semiconductor laser communications; LEDs; solar concentrators"]),
   'representative_works_json':J(["Double Heterostructure Lasers: Present Status and Future Developments (1976, Soviet Physics - Semiconductors)","Nobel lecture (2000): The Double Heterostructure Concept and Its Application"]),
   'fields_influenced':'semiconductor lasers, optoelectronics, solar cells, heterostructure physics',
   'cross_trunk_impact':'Fiber-optic communications revolution; LED lighting; photovoltaic technology',
   'contemporaries':'Herbert Kroemer (independent development), Izuo Hayashi (Bell Labs parallel), Jack Kilby',
   'controversies':'Cold War priority dispute with American groups; Soviet scientific isolation meant contributions less recognized in West',
   'source_ids':'SRC_094','confidence':'A','evidence_type':'E2'},

  # ── NANOTECHNOLOGY ─────────────────────────────────────────────────────────
  {'pioneer_id':'PION_228','name':'Gerd Binnig','birth_year':'1947','death_year':None,
   'nationality':'Germany','primary_fields':'surface science, nanotechnology, scanning probe microscopy',
   'contributions_summary':'Scanning tunneling microscope (STM, 1981, with Rohrer) — first atomic-resolution surface imaging; atomic force microscope (AFM, 1986, with Quate and Gerber); Nobel Physics 1986; IBM Zurich',
   'key_ideas_json':J(["STM principle (1981): quantum tunneling current between sharp tip and conducting surface depends exponentially on distance; scanning tip maps surface atom by atom","IBM atom logo (1989, with Eigler): STM used to position xenon atoms spelling IBM — first proof of precise atomic manipulation","AFM (1986): measures forces between tip and surface; works on insulators unlike STM; now ubiquitous in materials characterization"]),
   'representative_works_json':J(["Surface Studies by Scanning Tunneling Microscopy (1982, Physical Review Letters 49, with Rohrer)","Atomic Force Microscope (1986, Physical Review Letters, with Quate and Gerber)"]),
   'fields_influenced':'surface science, nanotechnology, materials characterization, biology (AFM)',
   'cross_trunk_impact':'Nanotechnology (CON_006) enabled by STM/AFM; biological imaging by AFM (Trunk 5)',
   'contemporaries':'Heinrich Rohrer (co-inventor), Christoph Gerber (AFM co-inventor), Don Eigler (atomic manipulation)',
   'controversies':'Initial STM results doubted by community; room-temperature operation of STM in first demonstration unexpected',
   'source_ids':'SRC_095','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_229','name':'Heinrich Rohrer','birth_year':'1933','death_year':'2013',
   'nationality':'Switzerland','primary_fields':'surface science, nanotechnology, scanning probe microscopy',
   'contributions_summary':'Scanning tunneling microscope (STM, 1981, with Binnig) — first atomic-resolution surface imaging; Nobel Physics 1986; IBM Zurich; first to image Si(111) 7×7 surface reconstruction',
   'key_ideas_json':J(["STM co-invention: conceptual basis of STM; realized that tunneling current could map surface topography at atomic scale","Si(111) 7×7 reconstruction: first STM image showing atomic structure of semiconductor surface — long-standing puzzle solved","Nanotechnology vision: Rohrer articulated vision of nanotechnology and positioned STM as foundational tool"]),
   'representative_works_json':J(["Surface Studies by Scanning Tunneling Microscopy (1982, Physical Review Letters 49, with Binnig)","Nobel lecture (1986): Scanning Tunneling Microscopy — From Birth to Adolescence"]),
   'fields_influenced':'surface science, nanotechnology, semiconductor surface physics',
   'cross_trunk_impact':'Enabled surface science revolution (CON_005); nanotechnology (CON_006)',
   'contemporaries':'Gerd Binnig (co-inventor), Christoph Gerber (IBM Zurich), Gerhard Ertl (surface chemistry)',
   'controversies':'Initial doubts about STM practicality; Nobel shared only with Binnig and Ernst Ruska (electron microscope — unrelated)',
   'source_ids':'SRC_095','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_230','name':'Richard Smalley','birth_year':'1943','death_year':'2005',
   'nationality':'USA','primary_fields':'nanotechnology, nanomaterials, fullerene chemistry',
   'contributions_summary':'Buckminsterfullerene discovery (1985, with Curl and Kroto) — soccer-ball-shaped C60 carbon cage; opened fullerene chemistry and carbon nanomaterials field; Nobel Chemistry 1996; Rice University; later advocate for nanotechnology and energy solutions',
   'key_ideas_json':J(["C60 buckminsterfullerene (1985): 60-carbon truncated icosahedral cage structure; stable and symmetric; discovered in laser ablation of graphite","Fullerene chemistry: C60 and higher fullerenes react with metals, form endohedral compounds; potential drug delivery vehicles","Carbon nanotubes connection: fullerene research led conceptually to single-walled carbon nanotubes"]),
   'representative_works_json':J(["C60: Buckminsterfullerene (1985, Nature 318, with Kroto, Heath, O'Brien, Curl)"]),
   'fields_influenced':'nanomaterials, fullerene chemistry, carbon science, nanotechnology',
   'cross_trunk_impact':'Drug delivery applications (Trunk 4/Medicine via nanotechnology); energy technology advocacy',
   'contemporaries':'Robert Curl (Nobel shared), Harold Kroto (Nobel shared), Sumio Iijima (carbon nanotubes)',
   'controversies':'Debate over mechanism of C60 formation; Kroto-Smalley collaboration became strained; Smalley vs Drexler debate on molecular nanotechnology feasibility',
   'source_ids':'SRC_095','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_231','name':'Robert Curl','birth_year':'1933','death_year':'2022',
   'nationality':'USA','primary_fields':'nanotechnology, fullerene chemistry, spectroscopy',
   'contributions_summary':'Buckminsterfullerene co-discovery (1985, with Smalley and Kroto); brought Kroto and Smalley together; laser spectroscopy; Nobel Chemistry 1996; Rice University professor',
   'key_ideas_json':J(["C60 co-discovery: provided expertise in laser ablation and molecular spectroscopy for the discovery experiment","Facilitator role: arranged collaboration between Smalley (laser ablation expertise) and Kroto (interstellar carbon molecules interest)","Spectroscopic analysis: mass spectrometry data interpretation confirming C60 structure"]),
   'representative_works_json':J(["C60: Buckminsterfullerene (1985, Nature 318)"]),
   'fields_influenced':'fullerene chemistry, carbon nanomaterials, spectroscopy',
   'cross_trunk_impact':'Carbon nanomaterials (CON_006); spectroscopic methods for nanomaterials',
   'contemporaries':'Richard Smalley (co-discoverer), Harold Kroto (co-discoverer), James Heath (graduate student)',
   'controversies':'Relative credit among three Nobel laureates contested; Curl often seen as less prominent despite key facilitating role',
   'source_ids':'SRC_095','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_232','name':'Harold Kroto','birth_year':'1939','death_year':'2016',
   'nationality':'UK','primary_fields':'nanotechnology, fullerene chemistry, astrochemistry',
   'contributions_summary':'Buckminsterfullerene co-discovery (1985, with Curl and Smalley); interest in carbon chains in interstellar medium led to collaboration; Nobel Chemistry 1996; Sussex University; later science education advocate',
   'key_ideas_json':J(["Interstellar carbon motivation: Kroto studying long carbon chains in space; sought to create them in lab, leading to C60 discovery","C60 structure proposal: icosahedral cage structure with hexagonal and pentagonal faces — like a soccer ball or Buckminster Fuller geodesic dome","Buckminster Fuller connection: named after R. Buckminster Fuller whose geodesic domes have similar topology"]),
   'representative_works_json':J(["C60: Buckminsterfullerene (1985, Nature 318)"]),
   'fields_influenced':'fullerene chemistry, astrochemistry, nanomaterials, carbon science',
   'cross_trunk_impact':'Astrochemistry (CON_012 / Trunk 6); science communication and education',
   'contemporaries':'Richard Smalley (co-discoverer), Robert Curl (co-discoverer), Sumio Iijima',
   'controversies':'Post-Nobel relationship with Smalley became adversarial; Drexler vs Smalley nanotechnology debate (Kroto sided with Smalley); science education advocacy over late career',
   'source_ids':'SRC_095','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_233','name':'Sumio Iijima','birth_year':'1939','death_year':None,
   'nationality':'Japan','primary_fields':'nanotechnology, carbon nanomaterials, electron microscopy',
   'contributions_summary':'Carbon nanotube discovery (1991) — helical tubular graphitic carbon structures with remarkable mechanical (100x stronger than steel) and electronic properties; multi-walled (1991) then single-walled with Bethune (1993); NEC Corporation; most cited paper without Nobel Prize',
   'key_ideas_json':J(["Multi-walled carbon nanotubes (1991): concentric cylindrical graphene sheets; diameter 4-30 nm; helical structure; discovered by HRTEM electron microscopy","Single-walled nanotubes (1993): single graphene sheet rolled into tube; electronic properties (metallic or semiconducting) depend on chirality","Nanotube properties: Young modulus ~1 TPa (stiffest known); conductance quantized; potential for transistors, composites, sensors"]),
   'representative_works_json':J(["Helical Microtubules of Graphitic Carbon (1991, Nature 354)"]),
   'fields_influenced':'nanomaterials, carbon science, nanotechnology, composites',
   'cross_trunk_impact':'Structural composites (Trunk 8); electronics (nanotransistors); energy storage',
   'contemporaries':'Richard Smalley (fullerenes), Millie Dresselhaus (carbon nanotubes theory), Don Bethune (single-walled CNTs)',
   'controversies':'Earlier Russian observations of similar structures disputed; Nobel Prize question (Kroto, Curl, Smalley received it for C60, not Iijima for CNTs); single-walled CNT simultaneous discovery with IBM',
   'source_ids':'SRC_095','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_234','name':'Don Eigler','birth_year':'1953','death_year':None,
   'nationality':'USA','primary_fields':'nanotechnology, surface science, scanning probe microscopy',
   'contributions_summary':'First manipulation of individual atoms using STM (1989, IBM Almaden) — spelled "IBM" using 35 xenon atoms on nickel surface at 4K; quantum corral (1993) — circular atom arrangement creating quantum electron standing waves; proved atom-by-atom construction possible',
   'key_ideas_json':J(["Individual atom manipulation (1989): first controlled repositioning of individual atoms using STM; xenon on Ni(110) at 4K","IBM logo (1990, published 1990): spelled IBM with 35 Xe atoms — landmark demonstration of atomic-scale control","Quantum corral (1993): 48 iron atoms arranged in circle on Cu(111); electron standing waves visualized inside corral by STM"]),
   'representative_works_json':J(["Positioning Single Atoms with a Scanning Tunnelling Microscope (1990, Nature 344)"]),
   'fields_influenced':'nanotechnology, surface science, quantum phenomena visualization',
   'cross_trunk_impact':'Demonstrated fundamental limit of information storage; quantum computing conceptual visualization',
   'contemporaries':'Gerd Binnig and Heinrich Rohrer (STM inventors), Gerhard Ertl (surface science)',
   'controversies':'Low temperature requirement (4K) limits practical atom manipulation; debate over practical path to molecular machines from this approach',
   'source_ids':'SRC_095','confidence':'A','evidence_type':'E2'},

  # ── COMPUTATIONAL CHEMISTRY ────────────────────────────────────────────────
  {'pioneer_id':'PION_235','name':'Walter Kohn','birth_year':'1923','death_year':'2016',
   'nationality':'Austria/USA','primary_fields':'computational chemistry, condensed matter physics, DFT',
   'contributions_summary':'Density functional theory: Hohenberg-Kohn theorem (1964) and Kohn-Sham equations (1965); DFT reduces many-electron problem from 3N to 3 dimensions; Nobel Chemistry 1998; UCSB; also contributed to solid state physics (shallow impurity states, localization)',
   'key_ideas_json':J(["Hohenberg-Kohn theorem (1964): ground state of many-electron system uniquely determined by electron density n(r) — basis of DFT","Kohn-Sham equations (1965): practical DFT scheme using fictitious non-interacting electron system with same density as real system; exchange-correlation functional","Exchange-correlation approximations: local density approximation (LDA) makes DFT computationally tractable","DFT dominance: now most widely used quantum mechanical method in chemistry and materials science"]),
   'representative_works_json':J(["Inhomogeneous Electron Gas (1964, Physical Review 136, with Hohenberg)","Self-Consistent Equations Including Exchange and Correlation Effects (1965, Physical Review 140, with Sham)"]),
   'fields_influenced':'computational chemistry, materials science, condensed matter, biochemistry',
   'cross_trunk_impact':'DFT used in drug design (Trunk 4/biochemistry); materials discovery (CON_003); surface catalysis (CON_005)',
   'contemporaries':'Lu Jeu Sham (co-developer), John Pople (Nobel shared 1998), Pierre Hohenberg (co-author)',
   'controversies':'DFT Nobel Chemistry (not Physics) debated since Kohn primarily physicists application; exchange-correlation functional approximations remain active research area',
   'source_ids':'SRC_097, SRC_098','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_236','name':'John Pople','birth_year':'1925','death_year':'2004',
   'nationality':'UK/USA','primary_fields':'computational chemistry, quantum chemistry',
   'contributions_summary':'Gaussian software package (1970s) making quantum chemistry calculations accessible to non-specialists; Hartree-Fock implementation; basis set development; approximation methods (CNDO, INDO semi-empirical); Nobel Chemistry 1998 shared with Kohn',
   'key_ideas_json':J(["GAUSSIAN software (1970s onward): code implementing HF and post-HF quantum chemistry calculations; democratized computational chemistry","Gaussian basis sets: mathematical basis functions for molecular orbital calculations; Pople basis sets (STO-3G, 6-31G*, etc.) widely used","Semi-empirical methods (CNDO, INDO, 1965-1970): parameterized quantum chemistry for larger molecules","Post-HF electron correlation: MP2, CISD methods implemented; hierarchy of approximations"]),
   'representative_works_json':J(["Approximate Self-Consistent Molecular Orbital Theory (1965, Journal of Chemical Physics, CNDO)","GAUSSIAN 70 (1970, first release)"]),
   'fields_influenced':'computational chemistry, organic chemistry, biochemistry, drug design',
   'cross_trunk_impact':'Drug design via molecular orbital calculations (Trunk 4); biochemistry simulations (Trunk 5)',
   'contemporaries':'Walter Kohn (Nobel shared), Axel Becke (DFT functionals), Martin Head-Gordon (post-HF methods)',
   'controversies':'Pople withdrew from authorship of highly cited papers involving others as scientific community grew; GAUSSIAN software commercial licensing criticized; ethics concerns regarding authorship practices',
   'source_ids':'SRC_098','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_237','name':'Robert S. Mulliken','birth_year':'1896','death_year':'1986',
   'nationality':'USA','primary_fields':'quantum chemistry, molecular orbital theory',
   'contributions_summary':'Molecular orbital (MO) theory (1920s-1930s) — electrons belong to whole molecule, not individual atoms; Mulliken charges (population analysis); electronic spectra of molecules; Nobel Chemistry 1966; Chicago',
   'key_ideas_json':J(["Molecular orbital theory (MO): electrons occupy orbitals delocalized over entire molecule — contrast to valence bond (VB) theory; correct quantum mechanical framework","LCAO approximation: molecular orbitals as linear combinations of atomic orbitals (LCAO-MO); basis for all quantum chemistry","Mulliken population analysis: partitioning electron density among atoms; Mulliken charges widely used","Electronic spectra: MO theory explains UV-visible absorption of molecules; band assignments"]),
   'representative_works_json':J(["Electronic States and Band Spectrum Structure in Diatomic Molecules (1928, Physical Review)","Nobel lecture: Spectroscopy, Molecular Orbitals, and Chemical Bonding (1966)"]),
   'fields_influenced':'quantum chemistry, spectroscopy, computational chemistry, biochemistry',
   'cross_trunk_impact':'Biochemistry (Trunk 5) — electronic structure of biomolecules; pharmaceutical chemistry (HOMO/LUMO drug binding)',
   'contemporaries':'Linus Pauling (valence bond rival), John Lennard-Jones (MO theory parallel), Friedrich Hund (MO co-originator)',
   'controversies':'MO vs valence bond (VB) theory rivalry with Pauling throughout career; both approaches now understood as limiting cases; delayed Nobel (1966 for 1930s work)',
   'source_ids':'SRC_098','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_238','name':'Axel D. Becke','birth_year':'1953','death_year':None,
   'nationality':'Canada','primary_fields':'computational chemistry, DFT, exchange-correlation functionals',
   'contributions_summary':'B3LYP exchange-correlation functional (1993) — most widely cited paper in all of scientific literature (~100,000 citations); DFT functional development; exchange energy functional (Becke 1988); Queen\'s University and Dalhousie; transformed DFT from physics tool to routine chemistry tool',
   'key_ideas_json':J(["B3LYP functional (1993): hybrid exchange-correlation functional mixing exact HF exchange with DFT; first functional accurate enough for organic chemistry bond energies","Becke-88 exchange (1988): improved exchange energy functional based on inhomogeneity correction","Hybrid functionals: mixing exact exchange with DFT correlation — generalization producing \"Jacob's ladder\" of functional accuracy"]),
   'representative_works_json':J(["Density-functional exchange-energy approximation with correct asymptotic behavior (1988, Physical Review A 38)","A new mixing of Hartree-Fock and local density-functional theories (1993, Journal of Chemical Physics)"]),
   'fields_influenced':'computational chemistry, organic chemistry, biochemistry, materials chemistry',
   'cross_trunk_impact':'Drug design (most widely used method for molecular energetics); catalysis design',
   'contemporaries':'Walter Kohn (DFT founder), John Pople (Gaussian code), Lee and Yang and Parr (LYP correlation)',
   'controversies':'B3LYP overused even where inappropriate; debate over systematic improvement of functionals vs empirical parameterization',
   'source_ids':'SRC_098','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_239','name':'Gerhard Ertl','birth_year':'1936','death_year':None,
   'nationality':'Germany','primary_fields':'surface science, heterogeneous catalysis, surface chemistry',
   'contributions_summary':'Surface chemistry of heterogeneous catalysis; molecular mechanism of Haber-Bosch process (N2 dissociation on iron at atomic level); CO oxidation on platinum mechanism; Nobel Chemistry 2007; Fritz Haber Institute Berlin',
   'key_ideas_json':J(["Haber-Bosch mechanism (1970s-1980s): N2 adsorption and dissociation on Fe(111) surface resolved step by step using LEED, Auger, thermal desorption","CO oxidation on Pt: Langmuir-Hinshelwood mechanism confirmed; oscillatory reaction kinetics on Pt(110)","Surface reaction dynamics: real-time imaging of surface chemical reactions using PEEM and other techniques","Langmuir-Hinshelwood mechanism: reactants adsorb on surface then react; general framework for heterogeneous catalysis"]),
   'representative_works_json':J(["Elementary Steps in the Catalytic Synthesis of Ammonia (1980s, multiple papers in Surface Science and Journal of Catalysis)","Nobel lecture: Reactions at Surfaces (2007)"]),
   'fields_influenced':'surface science, heterogeneous catalysis, chemical engineering, environmental catalysis',
   'cross_trunk_impact':'Industrial catalysis (Trunk 8) — Haber-Bosch understanding; automotive catalysts (three-way catalyst); environmental chemistry',
   'contemporaries':'Gabor Somorjai (surface chemistry, Berkeley), Klaus Christmann (surface chemistry), Binnig and Rohrer (STM enabled surface work)',
   'controversies':'Ertl exclusively studied well-defined single crystal surfaces; debate over relevance to industrial supported catalysts',
   'source_ids':'SRC_098','confidence':'A','evidence_type':'E2'},

  # ── QUANTUM COMPUTING ──────────────────────────────────────────────────────
  {'pioneer_id':'PION_240','name':'Peter Shor','birth_year':'1959','death_year':None,
   'nationality':'USA','primary_fields':'quantum computing, quantum algorithms, cryptography',
   'contributions_summary':'Shor\'s algorithm (1994) — quantum algorithm for integer factoring with exponential speedup over best classical algorithms; threatens RSA and public-key cryptography; quantum error correction (1995); Bell Labs and MIT; established quantum computing\'s strategic importance',
   'key_ideas_json':J(["Shor's algorithm (1994): factoring N-digit integer using quantum Fourier transform in O(N^3) operations vs classical O(exp(N^1/3)) — exponential speedup","Quantum error correction (1995): first quantum error correcting code; showed quantum computation is fault-tolerant in principle","Post-quantum cryptography driver: Shor's algorithm created urgency for NIST post-quantum cryptography competition (2016-2022)"]),
   'representative_works_json':J(["Algorithms for Quantum Computation: Discrete Logarithms and Factoring (1994, Proceedings 35th FOCS)","Scheme for Reducing Decoherence in Quantum Computer Memory (1995, Physical Review A)"]),
   'fields_influenced':'quantum computing, cryptography, computer science, number theory',
   'cross_trunk_impact':'Cryptography and internet security (Computer Science); drove NIST post-quantum standards',
   'contemporaries':'Lov Grover (Grover search algorithm), David Deutsch (first quantum algorithm), Peter Shor (Bell Labs then MIT)',
   'controversies':'Practical quantum computer to implement Shor\'s algorithm for cryptographically relevant sizes still decades away per most estimates; threat real but timeline uncertain',
   'source_ids':'SRC_103, SRC_104','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_241','name':'David Wineland','birth_year':'1944','death_year':None,
   'nationality':'USA','primary_fields':'quantum computing, atomic physics, precision measurement',
   'contributions_summary':'Laser cooling of trapped ions to near absolute zero; quantum state manipulation of individual ions; first quantum logic operations using ions; atomic clock with optical lattice trap; Nobel Physics 2012 shared with Serge Haroche; NIST Boulder',
   'key_ideas_json':J(["Trapped ion quantum computing: individual ions in electromagnetic trap manipulated by laser pulses; long coherence times","First quantum logic gate (1995): CNOT gate demonstrated with two trapped 9Be+ ions at NIST","Laser cooling: Doppler cooling and sideband cooling of trapped ions to motional ground state","Optical atomic clocks: single-ion clocks (Al+, Hg+) most precise timekeeping devices; frequency uncertainty 10^-18"]),
   'representative_works_json':J(["Demonstration of a Fundamental Quantum Logic Gate (1995, Physical Review Letters, with Monroe et al.)"]),
   'fields_influenced':'quantum computing, atomic physics, precision measurement, metrology',
   'cross_trunk_impact':'Atomic clocks (GPS, gravitational wave detection); quantum simulation',
   'contemporaries':'Serge Haroche (Nobel shared, cavity QED approach), Rainer Blatt (trapped ion QC), Chris Monroe (NIST then IQM)',
   'controversies':'Trapped ion vs superconducting qubit platform competition; scaling trapped ion systems to many qubits challenging',
   'source_ids':'SRC_103','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_242','name':'John Preskill','birth_year':'1953','death_year':None,
   'nationality':'USA','primary_fields':'quantum computing, quantum information theory',
   'contributions_summary':'Quantum information theory; coined "quantum supremacy" (2012) and "NISQ" (noisy intermediate-scale quantum, 2018); quantum error correction theory; organized quantum computing community; Caltech lecture notes widely used; organized Google/Caltech quantum computing collaborations',
   'key_ideas_json':J(["NISQ era (2018): quantum computers with 50-1000 qubits but too noisy for error correction — current phase of quantum computing","Quantum supremacy (2012): point at which quantum computer solves problem infeasible for any classical computer in reasonable time","Topological quantum computing: use of non-Abelian anyons (topological states) for inherently fault-tolerant computation","Quantum error correction threshold theorem: if physical error rate below threshold, logical error rate arbitrarily reducible"]),
   'representative_works_json':J(["Quantum Computing in the NISQ Era and Beyond (2018, Quantum 2: 79)","Lecture Notes on Quantum Computation (ongoing, Caltech, widely used)"]),
   'fields_influenced':'quantum computing, quantum information, topological quantum matter',
   'cross_trunk_impact':'Quantum cryptography and communication; condensed matter (topological quantum computing connection)',
   'contemporaries':'Peter Shor (Bell Labs then MIT), Alexei Kitaev (topological QC), John Martinis (Google Quantum AI)',
   'controversies':'Google "quantum supremacy" paper (2019) co-led by his group; IBM disputed supremacy claim; NISQ timeline optimism debated',
   'source_ids':'SRC_104','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_243','name':'Alain Aspect','birth_year':'1947','death_year':None,
   'nationality':'France','primary_fields':'quantum optics, quantum entanglement, atomic physics',
   'contributions_summary':'First definitive experimental tests of Bell inequalities with correlated photons (1982) — loophole-free violated inequalities; confirmed quantum non-locality and entanglement; Nobel Physics 2022 shared with Clauser and Zeilinger; Institut d\'Optique',
   'key_ideas_json':J(["Bell test (1982): photon polarization correlations from Ca cascade violate Bell inequality by 40+ standard deviations — experiment free of locality and detection loopholes (via fast switching)","Quantum non-locality confirmed: results inconsistent with any local hidden variable theory; quantum mechanics genuinely non-local","Entanglement reality: spooky action at a distance (Einstein) confirmed real; basis for quantum cryptography"]),
   'representative_works_json':J(["Experimental Tests of Bell's Inequalities Using Time-Varying Analyzers (1982, Physical Review Letters 49)"]),
   'fields_influenced':'quantum optics, quantum information, quantum foundations, quantum cryptography',
   'cross_trunk_impact':'Quantum cryptography (QKD protocols); quantum communication; quantum computing foundations',
   'contemporaries':'John Clauser (Nobel shared, first Bell test 1972), Anton Zeilinger (Nobel shared, teleportation), Nicolas Gisin (quantum cryptography)',
   'controversies':'Earlier Bell tests (Clauser 1972, Freedman-Clauser 1972) had loopholes Aspect closed; 2015 loophole-free Bell test by Delft group further closed remaining loopholes',
   'source_ids':'SRC_103','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_244','name':'John Clauser','birth_year':'1942','death_year':None,
   'nationality':'USA','primary_fields':'quantum optics, quantum entanglement, quantum foundations',
   'contributions_summary':'First experimental test of Bell inequalities (1972, with Freedman) — confirmed quantum mechanics vs local hidden variables; CHSH inequality (Clauser-Horne-Shimony-Holt, 1969); Nobel Physics 2022; worked on quantum foundations when it was unfashionable',
   'key_ideas_json':J(["CHSH inequality (1969): generalized Bell inequality testable with real imperfect experiments; with Horne, Shimony, Holt","First Bell test (1972): Ca atomic cascade photon correlations violate CHSH inequality — quantum mechanics wins over local hidden variables","Hidden variable theories: systematic experimental exclusion of all local realistic hidden variable theories"]),
   'representative_works_json':J(["Proposed Experiment to Test Local Hidden-Variable Theories (1969, Physical Review Letters, CHSH)","Experimental Test of Local Hidden-Variable Theories (1972, Physical Review Letters, with Freedman)"]),
   'fields_influenced':'quantum foundations, quantum optics, quantum information, quantum cryptography',
   'cross_trunk_impact':'Quantum cryptography protocols; quantum teleportation; quantum key distribution',
   'contemporaries':'Alain Aspect (Nobel shared), Anton Zeilinger (Nobel shared), John Bell (theoretical framework)',
   'controversies':'Worked on quantum foundations when most physicists considered it philosophy not physics; struggled for academic positions; Nobel came 50 years after work',
   'source_ids':'SRC_103','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_245','name':'Anton Zeilinger','birth_year':'1945','death_year':None,
   'nationality':'Austria','primary_fields':'quantum optics, quantum information, quantum teleportation',
   'contributions_summary':'Quantum teleportation (1997) — first teleportation of quantum state; quantum cryptography experiments; entanglement swapping; loophole-free Bell tests; Nobel Physics 2022; Vienna; Institute for Quantum Optics and Quantum Information',
   'key_ideas_json':J(["Quantum teleportation (1997): quantum state of photon transmitted to distant photon using entanglement and classical communication — first quantum teleportation","Entanglement swapping: two photons that never interacted can become entangled via entanglement with common partner — quantum network element","Satellite quantum teleportation: demonstration of quantum communication over 1200 km (Chinese satellite Micius, 2017)"]),
   'representative_works_json':J(["Experimental Quantum Teleportation (1997, Nature 390)"]),
   'fields_influenced':'quantum information, quantum cryptography, quantum networks, quantum optics',
   'cross_trunk_impact':'Quantum internet foundations; quantum cryptography (QKD); quantum satellite communications',
   'contemporaries':'Alain Aspect (Nobel shared), John Clauser (Nobel shared), Nicolas Gisin (Geneva quantum group)',
   'controversies':'Quantum teleportation does not allow faster-than-light communication despite name; media misrepresentation common',
   'source_ids':'SRC_103','confidence':'A','evidence_type':'E2'},

  # ── ADDITIONAL NOTABLE PIONEERS ────────────────────────────────────────────
  {'pioneer_id':'PION_246','name':'Kai Siegbahn','birth_year':'1918','death_year':'2007',
   'nationality':'Sweden','primary_fields':'surface science, electron spectroscopy, X-ray physics',
   'contributions_summary':'X-ray photoelectron spectroscopy (XPS / ESCA — electron spectroscopy for chemical analysis) — analytical surface technique determining element composition and chemical state; Nobel Physics 1981; Uppsala University; son of Manne Siegbahn (1924 Nobel X-rays)',
   'key_ideas_json':J(["XPS/ESCA development (1960s): bombard surface with X-rays; measure kinetic energy of emitted electrons; determine element composition and chemical state from binding energies","Chemical shifts: XPS binding energies shift depending on chemical environment of atom — identifies oxidation state, bonding","Surface sensitivity: XPS samples only top 1-10 nm — surface analytical technique par excellence"]),
   'representative_works_json':J(["ESCA: Atomic, Molecular and Solid State Structure Studied by Means of Electron Spectroscopy (1967, Almqvist and Wiksell)"]),
   'fields_influenced':'surface science, analytical chemistry, materials characterization',
   'cross_trunk_impact':'Industrial quality control (Trunk 8 — semiconductor, thin film characterization); catalysis characterization',
   'contemporaries':'Gerhard Ertl (surface science), Gerd Binnig and Heinrich Rohrer (STM), Gabor Somorjai',
   'controversies':'Father Manne Siegbahn (1924 Nobel for X-ray spectroscopy); unusual family Nobel tradition; XPS Nobel 1981 vs Binnig-Rohrer STM Nobel 1986',
   'source_ids':'SRC_090','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_247','name':'Kenneth Wilson','birth_year':'1936','death_year':'2013',
   'nationality':'USA','primary_fields':'condensed matter physics, quantum field theory, renormalization group',
   'contributions_summary':'Renormalization group (1971-1974) — explains universal behavior near critical points; critical phenomena and second-order phase transitions; numerical lattice gauge theory; Nobel Physics 1982; Cornell and Ohio State',
   'key_ideas_json':J(["Renormalization group for critical phenomena (1971-1974): systematic procedure for integrating out short-wavelength fluctuations; explains why different systems share same critical exponents near phase transitions","Universality classes: systems with same symmetry and dimensionality have same critical exponents regardless of microscopic details","Numerical lattice QCD: first numerical methods for calculating QCD properties from first principles; lattice regularization","Kondo problem: applied RG to explain resistance minimum in metals with magnetic impurities"]),
   'representative_works_json':J(["Renormalization Group and Critical Phenomena I, II (1971, Physical Review B 4)"]),
   'fields_influenced':'condensed matter, particle physics, critical phenomena, lattice QCD',
   'cross_trunk_impact':'QCD calculations (particle physics, CON_001); statistical mechanics phase transition universal behavior',
   'contemporaries':'Leo Kadanoff (block spin RG), Michael Fisher (critical phenomena), Franz Wegner',
   'controversies':'Wilson vs Kadanoff credit for renormalization group approach; Wilson more formal mathematical; Kadanoff physical block spin picture came first',
   'source_ids':'SRC_091','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_248','name':'Leo Kadanoff','birth_year':'1937','death_year':'2015',
   'nationality':'USA','primary_fields':'condensed matter physics, critical phenomena, statistical mechanics',
   'contributions_summary':'Block spin renormalization (1966) — physical picture of renormalization group; scaling hypothesis for critical phenomena; critical exponent scaling laws; connections to phase transition universality; Chicago and Brown',
   'key_ideas_json':J(["Block spin picture (1966): group nearby spins into blocks; integrate out short-wavelength fluctuations to get effective theory at longer wavelengths — physical basis for Wilson RG","Scaling hypothesis: near critical point, free energy has scaling form depending only on relevant variables","Scaling laws: derives relations among critical exponents from scaling hypothesis","Applications to turbulence: Kadanoff contributions to complexity and non-equilibrium phenomena"]),
   'representative_works_json':J(["Scaling Laws for Ising Models Near Tc (1966, Physics 2: 263)"]),
   'fields_influenced':'condensed matter, statistical mechanics, critical phenomena, turbulence',
   'cross_trunk_impact':'Statistical physics of complex systems; connections to information theory via entropy scaling',
   'contemporaries':'Kenneth Wilson (renormalization group), Michael Fisher (critical phenomena), B. Widom (scaling hypothesis)',
   'controversies':'Kadanoff block spin picture vs Wilson formal RG — which deserves Nobel; Wilson received it alone (1982)',
   'source_ids':'SRC_091','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_249','name':'Martin Karplus','birth_year':'1930','death_year':None,
   'nationality':'Austria/USA','primary_fields':'theoretical chemistry, molecular dynamics, biochemistry',
   'contributions_summary':'Molecular dynamics simulations of biomolecules — CHARMM force field and simulation package (1983); first MD simulation of a protein (BPTI, 1977); multiscale QM/MM methods; Karplus equation (NMR coupling constants); Nobel Chemistry 2013 shared with Levitt and Warshel; Harvard',
   'key_ideas_json':J(["Protein MD simulation (1977): first molecular dynamics of folded protein (bovine pancreatic trypsin inhibitor); 9.2 ps trajectory; revealed internal flexibility","CHARMM force field: parameterized force field for proteins, nucleic acids, lipids; CHARMM software package widely used","QM/MM multiscale method: quantum mechanics for active site, molecular mechanics for environment; enables enzyme mechanism calculation","Karplus equation: relation between vicinal NMR coupling constant and dihedral angle — structural chemistry tool"]),
   'representative_works_json':J(["Dynamics of Folded Proteins (1977, Nature, with McCammon and Gelin)","CHARMM: A Program for Macromolecular Energy, Minimization, and Dynamics Calculations (1983)"]),
   'fields_influenced':'computational chemistry, structural biology, biochemistry, drug design',
   'cross_trunk_impact':'Drug design (Trunk 4); protein folding (Trunk 5 Biology); enzyme mechanisms',
   'contemporaries':'Michael Levitt (Nobel shared), Arieh Warshel (Nobel shared), William Jorgensen (OPLS force field)',
   'controversies':'QM/MM Nobel Chemistry 2013 given for methods developed in 1970s-1980s; some felt Nobel should have recognized other computational biology contributions',
   'source_ids':'SRC_098','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_250','name':'Michael Levitt','birth_year':'1947','death_year':None,
   'nationality':'UK/South Africa/USA','primary_fields':'computational chemistry, structural biology, protein folding',
   'contributions_summary':'Multiscale molecular simulations including protein folding prediction (simplified models); QM/MM co-development; ENCAD force field; early protein structure prediction; Nobel Chemistry 2013 shared with Karplus and Warshel; Stanford',
   'key_ideas_json':J(["Simplified protein models (1975): coarse-grained protein models enabling folding simulations at longer timescales than all-atom MD","QM/MM method (1976): quantum mechanical treatment of chemically active region; molecular mechanics for protein environment — co-developed with Warshel","ENCAD force field: energy refinement force field for protein structures","Protein secondary structure prediction: early computational approaches to predicting alpha helices and beta sheets"]),
   'representative_works_json':J(["Computer Simulation of Protein Folding (1975, Nature 253)"]),
   'fields_influenced':'computational biology, protein folding, drug design, structural biology',
   'cross_trunk_impact':'Drug design (Trunk 4); structural biology (Trunk 5); protein engineering',
   'contemporaries':'Martin Karplus (Nobel shared), Arieh Warshel (Nobel shared), David Baker (protein folding AI)',
   'controversies':'AlphaFold (AI protein folding, 2020) made many aspects of earlier computational methods obsolete; Nobel 2013 vs AI revolution timing',
   'source_ids':'SRC_098','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_251','name':'Chen-Ning Yang','birth_year':'1922','death_year':None,
   'nationality':'China/USA','primary_fields':'particle physics, statistical mechanics, gauge theory',
   'contributions_summary':'Parity non-conservation in weak interactions (1956, with Lee) — proposed experimental tests; Nobel Physics 1957 (fastest Nobel ever at that time: 1 year); Yang-Mills gauge theory (1954, with Mills) — mathematical framework for all modern particle physics (Standard Model gauge structure)',
   'key_ideas_json':J(["Parity violation (1956): showed existing evidence did not prove parity conservation in weak interactions; proposed experiments; Wu experiment confirmed","Yang-Mills theory (1954): non-Abelian gauge theory with SU(2) local symmetry; mathematical framework generalized to Standard Model","Lee-Yang lattice gas model: exact solution of 2D Ising model; connection between statistical mechanics and quantum field theory"]),
   'representative_works_json':J(["Question of Parity Conservation in Weak Interactions (1956, Physical Review 104, with Lee)","Conservation of Isotopic Spin and Isotopic Gauge Invariance (1954, Physical Review 96, with Mills)"]),
   'fields_influenced':'particle physics, quantum field theory, Standard Model, mathematical physics',
   'cross_trunk_impact':'Standard Model mathematical foundation; gauge theory as unifying framework',
   'contemporaries':'Tsung-Dao Lee (Nobel shared), Chien-Shiung Wu (parity violation experiment), Robert Mills (gauge theory co-author)',
   'controversies':'Yang-Mills theory initially rejected by Pauli at seminar (massless gauge bosons problem); now foundational; later Pauli acknowledged importance',
   'source_ids':'SRC_100','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_252','name':'Tsung-Dao Lee','birth_year':'1926','death_year':None,
   'nationality':'China/USA','primary_fields':'particle physics, quantum field theory, statistical mechanics',
   'contributions_summary':'Parity non-conservation in weak interactions (1956, with Yang) — proposed experimental tests; Nobel Physics 1957; Lee-Yang theorem on zeros of partition function; Lee model (quantum field theory renormalization); Columbia University',
   'key_ideas_json':J(["Parity violation (1956): theoretical analysis and proposed experimental tests showing parity need not be conserved in weak decay; overturned assumed symmetry","Lee-Yang theorem: complex zeros of partition function determine phase transitions — mathematical foundation of modern statistical mechanics","Lee model: soluble quantum field theory model used to study renormalization properties"]),
   'representative_works_json':J(["Question of Parity Conservation in Weak Interactions (1956, Physical Review 104, with Yang)","Statistical Theory of Equations of State and Phase Transitions I, II (1952, Physical Review, Lee-Yang)"]),
   'fields_influenced':'particle physics, statistical mechanics, quantum field theory, mathematical physics',
   'cross_trunk_impact':'Weak force understanding; statistical mechanics partition function theory',
   'contemporaries':'Chen-Ning Yang (Nobel shared), Chien-Shiung Wu (Wu experiment), Enrico Fermi (Columbia mentor)',
   'controversies':'Yang-Lee relationship later became strained; parity violation experiment credit to Wu not mentioned in Nobel',
   'source_ids':'SRC_100','confidence':'A','evidence_type':'E2'},

  {'pioneer_id':'PION_253','name':'George Whitesides','birth_year':'1939','death_year':None,
   'nationality':'USA','primary_fields':'nanotechnology, soft matter, self-assembly, bioanalytical chemistry',
   'contributions_summary':'Soft lithography methods; self-assembled monolayers (SAMs) on gold; microfluidics and lab-on-a-chip; "lab on paper" low-cost diagnostics; named most cited chemist of late 20th century; Harvard; exceptionally broad contributions to materials chemistry, nanotechnology, and biology interfaces',
   'key_ideas_json':J(["Soft lithography (1993+): PDMS-based patterning techniques; microcontact printing; enables patterning without clean room; democratized nanofabrication","Self-assembled monolayers (SAMs): ordered organic molecules self-assemble on gold surfaces via thiol-gold bond; controlled surface chemistry","Microfluidics/lab-on-chip: control of fluids in microchannel networks; diagnostics, drug testing, cell biology","Lab on paper: analytical chemistry on patterned paper; low-cost diagnostics for developing world"]),
   'representative_works_json':J(["Soft Lithography (1998, Angewandte Chemie, Annual Review of Materials Science)","Self-Assembled Monolayers of Thiolates on Metals (1996, Critical Reviews in Biochemistry)"]),
   'fields_influenced':'nanotechnology, soft matter, materials chemistry, bioanalytical chemistry, diagnostics',
   'cross_trunk_impact':'Medical diagnostics (Trunk 4); microfluidics for biology (Trunk 5); materials fabrication (Trunk 8)',
   'contemporaries':'Chad Mirkin (DNA nanomaterials), Paul Alivisatos (quantum dots), Alex Zettl (carbon nanotubes Berkeley)',
   'controversies':'Whitesides published highly critical Whitesides-Crabtree essay on energy research priorities; unconventional leadership style; exceptionally high citation count relative to Nobel recognition',
   'source_ids':'SRC_096','confidence':'A','evidence_type':'E2'},
]

print("Running Part 2: Contemporary Pioneers")
append_rows('pioneers.csv', PION_FIELDS, con_pioneers)
print(f"Part 2 complete. {len(con_pioneers)} contemporary pioneers added (PION_200-PION_253).")
