#!/usr/bin/env python3
"""
Part 5: Add MOD and CON field nodes (T3_MOD_001-011, T3_CON_001-012).
Run from project root: python3 05_validation/add_trunk3_part5_nodes.py
"""
import csv, json, os

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '04_nodes_edges')

def append_rows(fname, fieldnames, rows):
    path = os.path.join(BASE, fname)
    with open(path, 'a', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
        for r in rows:
            w.writerow(r)
    print(f"  + {fname}: {len(rows)} rows added")

NODE_FIELDS = ['node_id','label','type','trunk_id','parent_candidate','date_start','date_end',
               'date_precision','creation_event_type','region','description','core_idea',
               'pioneers','representative_works','institutional_markers','source_ids',
               'confidence','evidence_type','controversies','pioneer_ids',
               'enabling_breakthrough_ids','transforming_breakthrough_ids',
               'critical_works','critical_instruments']

nodes = [
  # ── MODERN NODES (T3_MOD_001-011) ──────────────────────────────────────────
  {'node_id':'T3_MOD_001','label':'Organic Chemistry','type':'field','trunk_id':'3',
   'parent_candidate':'T3_EMD_005',
   'date_start':'1828','date_end':'1950','date_precision':'year',
   'creation_event_type':'institutionalized_field','region':'European',
   'description':'Study of carbon compounds — their structure, properties, synthesis, and reactions. Emerged from defeat of vitalism (Wöhler urea synthesis, 1828) and structure theory (Kekulé, 1858-1865). Industry-driven (German dye industry, pharmaceuticals). Characterized by structural formulas, retrosynthesis, reaction mechanisms.',
   'core_idea':'Carbon forms four bonds and can chain into rings and networks, generating vast structural diversity; organic compounds obey the same chemical laws as inorganic materials (no vital force required); systematic synthesis requires understanding structural relationships.',
   'pioneers':'Friedrich Wöhler, Justus von Liebig, August Kekulé, Emil Fischer, Adolf von Baeyer, William Perkin',
   'representative_works':'Wöhler urea synthesis (1828); Kekulé benzene structure (1865); Fischer sugars and lock-and-key (1890s-1900s)',
   'institutional_markers':'Liebig Annalen (1832); German dye industry (1856+); separate organic chemistry chairs 1860s; Nobel Chemistry: Fischer 1902, Baeyer 1905',
   'source_ids':'SRC_076, SRC_085','confidence':'A','evidence_type':'E4',
   'controversies':'Vitalism persisted despite Wöhler; priority disputes (Kekulé vs Couper for chain theory; benzene dream story apocryphal); German monopoly on organic chemistry before WWI',
   'pioneer_ids':'PION_144, PION_145, PION_146',
   'enabling_breakthrough_ids':'BRKTH_048, BRKTH_050, BRKTH_039',
   'transforming_breakthrough_ids':'BRKTH_092, BRKTH_068',
   'critical_works':'Kekulé Über die Konstitution (1858); Fischer Untersuchungen über Kohlenhydrate (1884-1908)',
   'critical_instruments':'Combustion analysis apparatus; polarimeter (optical rotation); reflux condenser; Bunsen burner'},

  {'node_id':'T3_MOD_002','label':'Analytical Chemistry','type':'field','trunk_id':'3',
   'parent_candidate':'T3_EMD_005',
   'date_start':'1850','date_end':'1950','date_precision':'decade',
   'creation_event_type':'institutionalized_field','region':'European',
   'description':'Quantitative determination of substance composition and structure. Gravimetric, volumetric, spectroscopic, and electrochemical methods. Service discipline enabling all other sciences. Instrumentation-dependent and increasingly automated.',
   'core_idea':'Every substance has definite quantitative composition determinable by systematic analytical procedure; instrumentation extends sensitivity and selectivity; analytical methods require rigorous calibration and uncertainty estimation.',
   'pioneers':'Carl Remigius Fresenius, Gustav Kirchhoff, Robert Bunsen, Francis Aston, Mikhail Tswett',
   'representative_works':'Fresenius Anleitung zur qualitativen und quantitativen chemischen Analyse (1841, 1842); Kirchhoff-Bunsen spectroscopy (1860); Aston mass spectrograph (1919)',
   'institutional_markers':'Zeitschrift für analytische Chemie (1862); gravimetric analysis textbooks (Fresenius); mass spectrometry Nobel 1922 (Aston); chromatography Nobel 1952',
   'source_ids':'SRC_076','confidence':'A','evidence_type':'E4',
   'controversies':'Analytical chemistry as service discipline vs independent research field debate; spectroscopic methods initially resisted by classical analytical chemists',
   'pioneer_ids':'PION_185, PION_186, PION_194',
   'enabling_breakthrough_ids':'BRKTH_020, BRKTH_063, BRKTH_039',
   'transforming_breakthrough_ids':'BRKTH_080, BRKTH_087, BRKTH_093',
   'critical_works':'Fresenius Anleitung zur qualitativen chemischen Analyse (1841); Kirchhoff-Bunsen Chemical Analysis by Spectral Observations (1860)',
   'critical_instruments':'Gravimetric balance; burette (volumetric); prism spectroscope; mass spectrograph; chromatography column'},

  {'node_id':'T3_MOD_003','label':'Inorganic Chemistry','type':'field','trunk_id':'3',
   'parent_candidate':'T3_EMD_005',
   'date_start':'1860','date_end':'1950','date_precision':'decade',
   'creation_event_type':'institutionalized_field','region':'European',
   'description':'Study of non-carbon compounds and elements — their synthesis, structure, bonding, reactivity. Residual category after organic split; unified by coordination chemistry (Werner, 1890s) and periodic table. Less theoretically coherent than organic until quantum mechanical bonding theory (Pauling 1930s).',
   'core_idea':'Elements organize into periodic system reflecting underlying atomic structure; transition metal compounds form coordination geometries predictable from electronic structure; quantum mechanics explains chemical bonding in inorganic systems.',
   'pioneers':'Dmitri Mendeleev, Alfred Werner, Linus Pauling, Henry Moseley, Fritz Haber',
   'representative_works':'Mendeleev periodic table (1869); Werner coordination theory (1893-1913); Pauling The Nature of the Chemical Bond (1939)',
   'institutional_markers':'Inorganic chemistry chairs 1890s; coordination chemistry journals; Werner Nobel Chemistry 1913; Pauling Nobel Chemistry 1954',
   'source_ids':'SRC_076','confidence':'A','evidence_type':'E4',
   'controversies':'Inorganic chemistry as residual category with weak theoretical coherence until quantum mechanics; Werner coordination theory disputed until 1913 Nobel confirmation; Haber-Bosch process ethics (ammonia for fertilizers vs explosives)',
   'pioneer_ids':'PION_155, PION_154, PION_195',
   'enabling_breakthrough_ids':'BRKTH_050, BRKTH_068, BRKTH_039',
   'transforming_breakthrough_ids':'BRKTH_076, BRKTH_088',
   'critical_works':'Mendeleev Osnovy khimii (Principles of Chemistry, 1868-1871); Werner Über die Konstitution und Konfiguration von Verbindungen höherer Ordnung (1893)',
   'critical_instruments':'Spectrochemical analysis apparatus; crystal structure apparatus (X-ray); electrochemical cell'},

  {'node_id':'T3_MOD_004','label':'Physical Chemistry','type':'field','trunk_id':'3',
   'parent_candidate':'T3_EMD_005, T3_MOD_005',
   'date_start':'1887','date_end':'1950','date_precision':'year',
   'creation_event_type':'institutionalized_field','region':'European',
   'description':'Application of physics (thermodynamics, kinetics, quantum mechanics) to chemical problems. Emerged as formal field 1887 with founding of Zeitschrift für Physikalische Chemie. Bridges physics and chemistry: thermodynamic equilibria, reaction rates, electrochemistry, solution theory, molecular structure. MERGE: thermodynamics + chemistry.',
   'core_idea':'Chemical phenomena obey the same thermodynamic and kinetic laws as physical phenomena; equilibrium determined by free energy minimization; reaction rates by activation energy barriers; ionic dissociation explains solution conductivity.',
   'pioneers':'Jacobus van\'t Hoff, Svante Arrhenius, Wilhelm Ostwald, J. Willard Gibbs, Walther Nernst, Gilbert N. Lewis',
   'representative_works':'Zeitschrift für Physikalische Chemie (founded 1887); Gibbs On Equilibrium of Heterogeneous Substances (1876-1878); van\'t Hoff Études de Dynamique Chimique (1884)',
   'institutional_markers':'Zeitschrift für Physikalische Chemie (1887) FOUNDING MARKER; Leipzig chair Ostwald (1887); MIT program Noyes (1903); Berkeley Lewis (1912); Nobel: van\'t Hoff 1901, Arrhenius 1903, Ostwald 1909, Nernst 1920',
   'source_ids':'SRC_075','confidence':'A','evidence_type':'E4',
   'controversies':'Arrhenius ionic dissociation thesis nearly failed (graded near-fail 1884); Ostwald anti-atomism until 1908; Gibbs work unknown until Ostwald translated (1892); Lewis-Langmuir bonding theory priority dispute',
   'pioneer_ids':'PION_147, PION_148, PION_149, PION_150, PION_151, PION_152',
   'enabling_breakthrough_ids':'BRKTH_065, BRKTH_066, BRKTH_064',
   'transforming_breakthrough_ids':'BRKTH_069, BRKTH_076',
   'critical_works':'Zeitschrift für Physikalische Chemie vol.1 (1887); Gibbs On the Equilibrium of Heterogeneous Substances (1876-1878); Nernst Theoretische Chemie (1893)',
   'critical_instruments':'Galvanic cell; conductimetry apparatus; vapor pressure measurement; calorimeter; viscometer'},

  {'node_id':'T3_MOD_005','label':'Thermodynamics','type':'field','trunk_id':'3',
   'parent_candidate':'T3_EMD_003',
   'date_start':'1824','date_end':'1950','date_precision':'year',
   'creation_event_type':'named_field','region':'European',
   'description':'Study of heat, work, temperature, and energy in macroscopic systems. First law (energy conservation), second law (entropy and direction of time), third law (absolute zero entropy). Developed 1824-1865, becomes physics specialty. Foundation for all of chemistry via free energy.',
   'core_idea':'Energy is conserved; entropy of isolated systems never decreases; heat flows spontaneously from hot to cold; thermodynamic state functions predict equilibrium and spontaneous processes independent of mechanism.',
   'pioneers':'Sadi Carnot, James Prescott Joule, Rudolf Clausius, William Thomson (Lord Kelvin), Hermann von Helmholtz, J. Willard Gibbs',
   'representative_works':'Carnot Réflexions (1824); Clausius entropy papers (1850-1865); Gibbs Heterogeneous Substances (1876-1878)',
   'institutional_markers':'Integrated into physics curriculum 1870s; Clausius and Maxwell textbooks 1870s-1880s; thermodynamics specialty chairs; all physical chemistry depends on thermodynamics',
   'source_ids':'SRC_081','confidence':'A','evidence_type':'E4',
   'controversies':'Heat as caloric fluid theory lingered until 1840s; irreversibility and arrow of time philosophical controversy; Maxwell demon thought experiment; Boltzmann statistical foundation disputed by Mach',
   'pioneer_ids':'PION_156, PION_157, PION_158, PION_159, PION_160',
   'enabling_breakthrough_ids':'BRKTH_047, BRKTH_051, BRKTH_043',
   'transforming_breakthrough_ids':'BRKTH_065, BRKTH_066',
   'critical_works':'Carnot Réflexions sur la Puissance Motrice du Feu (1824); Clausius papers (1850-1865); Kelvin On the Dynamical Theory of Heat (1851)',
   'critical_instruments':'Steam engine (empirical basis); calorimeter; thermometer; pressure gauge'},

  {'node_id':'T3_MOD_006','label':'Electromagnetism','type':'field','trunk_id':'3',
   'parent_candidate':'T3_EMD_008',
   'date_start':'1820','date_end':'1950','date_precision':'decade',
   'creation_event_type':'named_field','region':'European',
   'description':'Unified theory of electricity, magnetism, and light as aspects of a single electromagnetic field. Developed 1820 (Oersted) through Maxwell equations (1864-1873) and Hertz experimental confirmation (1887). Foundation for all electromagnetic technology and quantum electrodynamics.',
   'core_idea':'Electricity and magnetism are two aspects of a single electromagnetic field; changing electric fields generate magnetic fields and vice versa; electromagnetic waves travel at speed of light; light is an electromagnetic wave.',
   'pioneers':'Hans Christian Oersted, André-Marie Ampère, Michael Faraday, James Clerk Maxwell, Heinrich Hertz, Oliver Heaviside',
   'representative_works':'Maxwell Treatise on Electricity and Magnetism (1873); Hertz Über Strahlen elektrischer Kraft (1888)',
   'institutional_markers':'Cavendish Laboratory (1874, Maxwell first director); Physical Society of London (1874); APS (1899); Maxwell equations as physics canon by 1890s',
   'source_ids':'SRC_083, SRC_084','confidence':'A','evidence_type':'E4',
   'controversies':'Action-at-a-distance vs field theory debate (1850s-1870s); ether as medium for EM waves (destroyed by Michelson-Morley 1887); Faraday vs continental mathematicians (Faraday intuitive, Ampère mathematical)',
   'pioneer_ids':'PION_162, PION_163, PION_164, PION_165, PION_166',
   'enabling_breakthrough_ids':'BRKTH_064, BRKTH_038, BRKTH_047',
   'transforming_breakthrough_ids':'BRKTH_067, BRKTH_071',
   'critical_works':'Maxwell A Treatise on Electricity and Magnetism (1873); Hertz Electric Waves (1893); Heaviside Electromagnetic Theory (1893-1912)',
   'critical_instruments':'Galvanometer; Leyden jar; induction coil; spark gap transmitter/receiver (Hertz)'},

  {'node_id':'T3_MOD_007','label':'Modern Optics and Spectroscopy','type':'field','trunk_id':'3',
   'parent_candidate':'T3_EMD_007',
   'date_start':'1859','date_end':'1950','date_precision':'year',
   'creation_event_type':'named_field','region':'European',
   'description':'Spectroscopy as systematic analytical method; precision interferometry; quantum explanation of spectral lines. Spectroscopy central to atomic physics and analytical chemistry. Spans optics and chemistry/physics interface.',
   'core_idea':'Each element has a unique spectral fingerprint detectable by emission/absorption; spectral line positions correspond to quantized electron energy level transitions; interferometry enables precision light speed measurement.',
   'pioneers':'Gustav Kirchhoff, Robert Bunsen, Albert A. Michelson, Johann Balmer, Johannes Rydberg',
   'representative_works':'Kirchhoff-Bunsen Chemische Analyse durch Spectralbeobachtungen (1860); Michelson-Morley null result (1887); Balmer series formula (1885)',
   'institutional_markers':'Spectroscopy as standard tool by 1870s; Michelson Nobel Physics 1907 (first American Nobel in science); Zeeman effect Nobel 1902; spectroscopy in all physics/chemistry curricula by 1890s',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E4',
   'controversies':'Spectral line origin unknown until Bohr model (1913); ether concept as spectral propagation medium; Zeeman-Lorentz controversy over electron theory of spectral splitting',
   'pioneer_ids':'PION_185, PION_186, PION_196',
   'enabling_breakthrough_ids':'BRKTH_056, BRKTH_067, BRKTH_036',
   'transforming_breakthrough_ids':'BRKTH_080, BRKTH_084',
   'critical_works':'Kirchhoff-Bunsen Spectroscopic Analysis (1860); Rowland grating spectra; Michelson-Morley (1887)',
   'critical_instruments':'Bunsen burner; prism spectroscope; diffraction grating; Michelson interferometer; photographic spectrograph'},

  {'node_id':'T3_MOD_008','label':'Atomic and Nuclear Physics','type':'field','trunk_id':'3',
   'parent_candidate':'T3_EMD_003, T3_MOD_006',
   'date_start':'1895','date_end':'1950','date_precision':'year',
   'creation_event_type':'institutionalized_field','region':'European',
   'description':'Study of atom internal structure, radioactivity, and nuclear reactions. Founded by X-ray and radioactivity discoveries (1895-1898), electron discovery (1897), nuclear atom (1911), culminating in nuclear fission (1938-1942). Spans atomic spectroscopy, nuclear structure, particle physics precursor.',
   'core_idea':'Atoms have internal structure (nucleus + electrons); nucleus composed of protons and neutrons; nuclear reactions release energy via E=mc²; radioactivity reveals spontaneous nuclear transmutation; subatomic particles governed by quantum mechanics.',
   'pioneers':'J.J. Thomson, Marie Curie, Ernest Rutherford, James Chadwick, Enrico Fermi, Lise Meitner, Otto Hahn',
   'representative_works':'Thomson cathode rays paper (1897); Rutherford nuclear atom (1911); Chadwick neutron (1932); Hahn-Meitner fission (1938-1939)',
   'institutional_markers':'Cavendish Laboratory nuclear physics (Rutherford director 1919); Nobel: Thomson 1906, Rutherford 1908, Curie (twice), Chadwick 1935, Fermi 1938; Manhattan Project (1942-1945)',
   'source_ids':'SRC_079, SRC_080','confidence':'A','evidence_type':'E4',
   'controversies':'Nuclear fission military application (Manhattan Project, Hiroshima); Meitner systematically excluded from Nobel despite co-discovering fission; Rutherford-Bohr model transition period; Nazi persecution of Jewish physicists causing brain drain',
   'pioneer_ids':'PION_168, PION_179, PION_180, PION_189, PION_190',
   'enabling_breakthrough_ids':'BRKTH_050, BRKTH_067, BRKTH_064',
   'transforming_breakthrough_ids':'BRKTH_081, BRKTH_082, BRKTH_083, BRKTH_076',
   'critical_works':'Thomson cathode rays (1897); Rutherford alpha scattering (1911); Bohr atomic model (1913); Chadwick neutron (1932)',
   'critical_instruments':'Cathode ray tube; cloud chamber; Geiger counter; alpha scattering apparatus; cyclotron; mass spectrograph'},

  {'node_id':'T3_MOD_009','label':'Quantum Mechanics','type':'theoretical_framework','trunk_id':'3',
   'parent_candidate':'T3_MOD_008, T3_MOD_005',
   'date_start':'1900','date_end':'1950','date_precision':'year',
   'creation_event_type':'conceptual_breakthrough','region':'European',
   'description':'Complete replacement of classical mechanics at atomic/subatomic scale. Energy quantized (Planck 1900); light quanta (Einstein 1905); de Broglie matter waves (1924); matrix mechanics (Heisenberg 1925); wave mechanics (Schrödinger 1926); uncertainty principle (Heisenberg 1927); relativistic QM (Dirac 1928). Most successful physical theory ever formulated.',
   'core_idea':'Physical observables are quantum operators; states described by wave functions whose squared modulus gives probability densities; uncertainty principle limits simultaneous precision of conjugate variables; energy, angular momentum, and other quantities are quantized.',
   'pioneers':'Max Planck, Albert Einstein, Niels Bohr, Louis de Broglie, Werner Heisenberg, Erwin Schrödinger, Max Born, Wolfgang Pauli, Paul Dirac',
   'representative_works':'Planck blackbody radiation (1900); Einstein photoelectric effect (1905); Heisenberg matrix mechanics (1925); Schrödinger wave mechanics (1926); Dirac Principles of Quantum Mechanics (1930)',
   'institutional_markers':'Copenhagen school (Bohr Institute); Nobel: Planck 1918, Einstein 1921, Bohr 1922, Heisenberg 1932, Schrödinger+Dirac 1933, Pauli 1945; quantum mechanics textbooks (Dirac 1930) canonical',
   'source_ids':'SRC_078, SRC_079','confidence':'A','evidence_type':'E4',
   'controversies':'Copenhagen vs Many-Worlds interpretation; Einstein-Bohr debates (God does not play dice); EPR paradox and hidden variables; quantum measurement problem still unresolved; wave function reality debate',
   'pioneer_ids':'PION_169, PION_170, PION_171, PION_172, PION_173, PION_174, PION_175, PION_176, PION_177',
   'enabling_breakthrough_ids':'BRKTH_070, BRKTH_073, BRKTH_075',
   'transforming_breakthrough_ids':'BRKTH_076, BRKTH_077, BRKTH_078, BRKTH_079',
   'critical_works':'Heisenberg matrix mechanics (1925); Schrödinger wave mechanics (1926); Dirac Principles of Quantum Mechanics (1930)',
   'critical_instruments':'Precision spectroscopic apparatus; Stern-Gerlach apparatus; electron diffraction (Davisson-Germer 1927)'},

  {'node_id':'T3_MOD_010','label':'Relativity (Special and General)','type':'theoretical_framework','trunk_id':'3',
   'parent_candidate':'T3_MOD_006',
   'date_start':'1905','date_end':'1950','date_precision':'year',
   'creation_event_type':'conceptual_breakthrough','region':'European',
   'description':'Special relativity (Einstein 1905): space and time are relative; c constant; E=mc²; Lorentz transformations. General relativity (Einstein 1915): gravity is spacetime curvature. Revolutionary replacements of absolute space/time and Newtonian gravity. Confirmed by eclipse (1919) and Mercury perihelion. Required for particle physics.',
   'core_idea':'Speed of light is constant for all observers; simultaneity is relative; mass and energy are equivalent (E=mc²); gravity is not a force but curvature of 4D spacetime caused by energy-momentum; no preferred reference frame.',
   'pioneers':'Albert Einstein, Hendrik Lorentz, Hermann Minkowski, Arthur Eddington, Henri Poincaré',
   'representative_works':'Einstein special relativity (1905); Einstein general relativity field equations (1915-1916); Eddington eclipse expedition (1919)',
   'institutional_markers':'Eddington eclipse 1919 confirmed GR and made Einstein famous; Einstein Nobel 1921 (for photoelectric effect, not relativity — Nobel committee uncertainty); GR entered physics curricula by 1930s',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E4',
   'controversies':'Lorentz-Poincaré vs Einstein priority for special relativity (Einstein credited for physical interpretation); resistance to relativity from anti-Semitic "Deutsche Physik" movement; GR vs quantum mechanics incompatibility unresolved',
   'pioneer_ids':'PION_170, PION_181, PION_182, PION_183',
   'enabling_breakthrough_ids':'BRKTH_067, BRKTH_084, BRKTH_047',
   'transforming_breakthrough_ids':'BRKTH_071, BRKTH_074',
   'critical_works':'Einstein Annalen der Physik 1905 papers; Minkowski Space and Time (1908); Schwarzschild exact solution (1916)',
   'critical_instruments':'Michelson interferometer; eclipse expedition instruments; spectroscopes (gravitational redshift)'},

  {'node_id':'T3_MOD_011','label':'Statistical Mechanics','type':'theoretical_framework','trunk_id':'3',
   'parent_candidate':'T3_MOD_005, T3_EMD_006',
   'date_start':'1860','date_end':'1950','date_precision':'decade',
   'creation_event_type':'modern_formulation','region':'European',
   'description':'Bridge between microscopic atomic/molecular behavior and macroscopic thermodynamic properties. Boltzmann\'s S=k log W (1870s); Gibbs ensemble theory (1902) named field; quantum statistics (Bose-Einstein, Fermi-Dirac, 1924-1926) added. MERGE: thermodynamics + atomic theory + kinetic theory.',
   'core_idea':'Thermodynamic properties are statistical averages over microscopic configurations (microstates); entropy measures number of accessible microstates (S = k log W); second law is probabilistic not absolute; quantum statistics required for indistinguishable particles.',
   'pioneers':'Ludwig Boltzmann, James Clerk Maxwell, J. Willard Gibbs, Albert Einstein, Jean Perrin',
   'representative_works':'Boltzmann kinetic theory papers (1870s-1890s); Gibbs Elementary Principles in Statistical Mechanics (1902); Perrin Les Atomes (1913)',
   'institutional_markers':'Gibbs 1902 treatise named field; Perrin Nobel 1926 for confirming atomistic interpretation; quantum statistics (1924-1926) extended into modern physics; foundation of condensed matter physics',
   'source_ids':'SRC_081, SRC_082','confidence':'A','evidence_type':'E4',
   'controversies':'Boltzmann-Mach debate on atomic reality (Mach denied atoms, drove Boltzmann to depression and suicide 1906); Loschmidt reversibility paradox; Zermelo recurrence paradox; statistical nature of second law troubling to contemporaries',
   'pioneer_ids':'PION_161, PION_165, PION_150, PION_170, PION_184',
   'enabling_breakthrough_ids':'BRKTH_065, BRKTH_066, BRKTH_050',
   'transforming_breakthrough_ids':'BRKTH_069, BRKTH_076',
   'critical_works':'Boltzmann Vorlesungen über Gastheorie (1896-1898); Gibbs Elementary Principles (1902); Einstein Brownian motion paper (1905)',
   'critical_instruments':'Ultramicroscope (Brownian motion observation); precision thermometry; calorimetry'},

  # ── CONTEMPORARY NODES (T3_CON_001-012) ────────────────────────────────────
  {'node_id':'T3_CON_001','label':'Quantum Field Theory and Quantum Electrodynamics','type':'theoretical_framework','trunk_id':'3',
   'parent_candidate':'T3_MOD_009, T3_MOD_010',
   'date_start':'1947','date_end':'2025','date_precision':'decade',
   'creation_event_type':'modern_formulation','region':'Global',
   'description':'Quantum-relativistic treatment of fields and particles. QED (photon-electron interactions) renormalized by Feynman, Schwinger, Tomonaga (1946-1949). Extended to electroweak unification (Glashow-Salam-Weinberg, 1967-1968), QCD (1973), Standard Model. Most precisely tested theory in physics; electron g-factor accurate to 12 significant figures.',
   'core_idea':'Fundamental particles are excitations of underlying quantum fields; interactions via exchange of virtual gauge bosons; renormalization makes calculations finite; gauge symmetry principles determine form of interactions; Standard Model describes all known particles and three of four fundamental forces.',
   'pioneers':'Richard Feynman, Julian Schwinger, Sin-Itiro Tomonaga, Freeman Dyson, Murray Gell-Mann, Steven Weinberg, David Gross, Peter Higgs',
   'representative_works':'Feynman QED path integral (1949); Dyson unification (1949); Weinberg Model of Leptons (1967); Gross-Wilczek asymptotic freedom (1973)',
   'institutional_markers':'Nobel: Feynman-Schwinger-Tomonaga 1965, Glashow-Salam-Weinberg 1979, Gross-Politzer-Wilczek 2004, Higgs-Englert 2013; Physical Review Letters dominant journal; CERN experiments confirmed W, Z bosons (1983), Higgs (2012)',
   'source_ids':'SRC_099, SRC_100','confidence':'A','evidence_type':'E4',
   'controversies':'Renormalization as mathematical trick criticized by Dirac; interpretation of virtual particles; Yang-Mills mass problem (resolved by Higgs mechanism); string theory attempts to go beyond Standard Model; gravity not included',
   'pioneer_ids':'PION_200, PION_201, PION_202, PION_203, PION_204, PION_205, PION_206, PION_207',
   'enabling_breakthrough_ids':'BRKTH_079, BRKTH_076, BRKTH_071',
   'transforming_breakthrough_ids':'BRKTH_095, BRKTH_100',
   'critical_works':'Schweber QED and the Men Who Made It (1994); Weinberg The Quantum Theory of Fields (1995)',
   'critical_instruments':'Particle accelerators (cyclotron lineage); CERN LHC; precision electron magnetic moment measurements'},

  {'node_id':'T3_CON_002','label':'Condensed Matter Physics','type':'field','trunk_id':'3',
   'parent_candidate':'T3_MOD_009, T3_MOD_011',
   'date_start':'1947','date_end':'2025','date_precision':'decade',
   'creation_event_type':'institutionalized_field','region':'Global',
   'description':'Study of collective properties of matter in condensed phases — electrons, atoms, molecules in solids, liquids, superconductors. Largest branch of physics by practitioners. Formerly solid state physics; renamed condensed matter physics (~1978) to include liquids, soft matter, complex systems. Bell Labs pivotal; topological materials active frontier.',
   'core_idea':'Collective emergent phenomena (superconductivity, magnetism, topological order) cannot be derived from individual particle behavior alone; quantum many-body physics governs condensed phases; topology classifies distinct phases of matter.',
   'pioneers':'John Bardeen, William Shockley, Philip Anderson, Nevill Mott, Leon Cooper, Brian Josephson, Klaus von Klitzing, Bednorz and Müller, Geim and Novoselov, Thouless, Haldane, Kosterlitz',
   'representative_works':'Bardeen-Cooper-Schrieffer BCS theory (1957); Anderson More is Different (1972); Ashcroft and Mermin Solid State Physics (1976); Bednorz-Müller high-Tc (1986)',
   'institutional_markers':'Bell Labs (transistor 1947, BCS 1957); APS Division of Solid State Physics (1947) renamed Condensed Matter Physics (~1978); Physical Review B (1970); Nobels: Bardeen 1956+1972, Josephson 1973, von Klitzing 1985, Bednorz-Müller 1987, Geim-Novoselov 2010, Thouless-Haldane-Kosterlitz 2016',
   'source_ids':'SRC_091, SRC_092, SRC_093','confidence':'A','evidence_type':'E4',
   'controversies':'High-Tc superconductivity mechanism unresolved 40+ years; topological insulator experimental realization decades after theory; condensed matter vs particle physics (Anderson vs Weinberg on emergence vs reductionism); strongly correlated electron systems computationally intractable',
   'pioneer_ids':'PION_208, PION_209, PION_210, PION_211, PION_212, PION_213, PION_214',
   'enabling_breakthrough_ids':'BRKTH_076, BRKTH_069, BRKTH_096',
   'transforming_breakthrough_ids':'BRKTH_097, BRKTH_098, BRKTH_103, BRKTH_104',
   'critical_works':'Anderson Basic Notions of CMP (1997); Ashcroft and Mermin (1976); BCS paper Physical Review (1957)',
   'critical_instruments':'Cryostats (liquid helium); SQUID magnetometer; scanning tunneling microscope; high magnetic field facilities'},

  {'node_id':'T3_CON_003','label':'Materials Science and Engineering','type':'field','trunk_id':'3',
   'parent_candidate':'T3_CON_002, T3_MOD_004',
   'date_start':'1960','date_end':'2025','date_precision':'decade',
   'creation_event_type':'institutionalized_field','region':'Global',
   'description':'Interdisciplinary field studying relationship between structure, processing, properties, and performance of materials at all length scales. Unified treatment of metals, ceramics, polymers, semiconductors, composites, biomaterials. MERGE: physics + chemistry + engineering, driven by ARPA IDL program (1960). Materials tetrahedron framework.',
   'core_idea':'Material properties determined by structure at all scales (atomic, microstructural, macroscopic); processing controls structure; structure determines properties; performance governed by properties; quantum mechanics provides unified theoretical framework for all material classes.',
   'pioneers':'Morris Cohen, Cyril Stanley Smith, Nevill Mott, William Hume-Rothery, A. H. Cottrell, Ernest Orowan',
   'representative_works':'ARPA IDL program documents (1960-1962); Journal of Materials Science (1966); Smith A History of Metallography (1960)',
   'institutional_markers':'ARPA IDLs at 12 universities (1960-1962) FOUNDING EVENT; Journal of Materials Science (1966); Materials Research Society (MRS, 1973); Acta Metallurgica → Acta Materialia (1996); metallurgy → materials science department renaming 1960s-1990s',
   'source_ids':'SRC_101','confidence':'A','evidence_type':'E4',
   'controversies':'Credit for founding materials science contested among universities; boundary with condensed matter physics and engineering unclear; materials tetrahedron criticized as too simplistic; cross-trunk parentage (also Trunk 8: Engineering)',
   'pioneer_ids':'PION_222, PION_223, PION_211, PION_208',
   'enabling_breakthrough_ids':'BRKTH_076, BRKTH_088, BRKTH_096',
   'transforming_breakthrough_ids':'BRKTH_110, BRKTH_099',
   'critical_works':'Journal of Materials Science vol. 1 (1966); Cottrell Dislocations and Plastic Flow in Crystals (1953); Smith History of Metallography (1960)',
   'critical_instruments':'Electron microscope; X-ray diffractometer; hardness tester; differential scanning calorimeter; synchrotron X-ray sources'},

  {'node_id':'T3_CON_004','label':'Quantum Chemistry and Computational Chemistry','type':'field','trunk_id':'3',
   'parent_candidate':'T3_MOD_009, T3_MOD_001, T3_MOD_004',
   'date_start':'1950','date_end':'2025','date_precision':'decade',
   'creation_event_type':'modern_formulation','region':'Global',
   'description':'Application of quantum mechanics to chemical systems; DFT as dominant method. Two overlapping areas: quantum chemistry (Hartree-Fock, post-HF) and computational chemistry (DFT, molecular dynamics, Monte Carlo). MERGE: quantum physics + chemistry + computing. Nobel Chemistry 1998 (Kohn + Pople) marks maturation.',
   'core_idea':'Chemical bonding and reactivity determined by quantum mechanical electronic structure; Density Functional Theory reduces many-electron problem to 3D electron density; computation enables calculation of properties impossible analytically; B3LYP functional works for organic chemistry.',
   'pioneers':'Walter Kohn, John Pople, Robert S. Mulliken, Axel Becke, Gerhard Ertl, Martin Karplus',
   'representative_works':'Hohenberg-Kohn DFT (1964); Kohn-Sham (1965); Gaussian software (1970s); Becke B3LYP (1993)',
   'institutional_markers':'Nobel Chemistry 1966 (Mulliken), 1998 (Kohn + Pople); Journal of Computational Chemistry (1980); GAUSSIAN software; Journal of Chemical Theory and Computation (2005)',
   'source_ids':'SRC_097, SRC_098','confidence':'A','evidence_type':'E4',
   'controversies':'DFT Nobel Chemistry not Physics (Kohn was physicist); GAUSSIAN software commercial restrictions criticized; B3LYP overuse (most cited paper ever but applied outside validity range); machine learning replacing DFT for some applications',
   'pioneer_ids':'PION_235, PION_236, PION_237, PION_238, PION_249',
   'enabling_breakthrough_ids':'BRKTH_076, BRKTH_099, BRKTH_108',
   'transforming_breakthrough_ids':'BRKTH_113, BRKTH_112',
   'critical_works':'Kohn Nobel lecture (1999); Cramer Essentials of Computational Chemistry (2004); Szabo and Ostlund Modern Quantum Chemistry (1989)',
   'critical_instruments':'High-performance computers; NMR spectrometers (validation); X-ray crystallography (structure validation)'},

  {'node_id':'T3_CON_005','label':'Surface Science and Interface Chemistry','type':'field','trunk_id':'3',
   'parent_candidate':'T3_MOD_004, T3_CON_002',
   'date_start':'1964','date_end':'2025','date_precision':'year',
   'creation_event_type':'institutionalized_field','region':'Global',
   'description':'Physical and chemical phenomena at surfaces and interfaces at atomic/molecular level. Ultra-high vacuum techniques and surface-sensitive probes (LEED, XPS, Auger, STM). Bridge between heterogeneous catalysis and condensed matter physics. Ertl resolved Haber-Bosch mechanism at atomic level (Nobel 2007).',
   'core_idea':'Surface atoms have different coordination and electronic structure from bulk; surface-to-volume ratio dominates at small scales; reaction mechanisms on surfaces differ from solution; clean surface experiments under UHV reveal elementary reaction steps.',
   'pioneers':'Gerhard Ertl, Gabor Somorjai, Gerd Binnig, Heinrich Rohrer, Kai Siegbahn',
   'representative_works':'Ertl N2 on Fe Haber-Bosch mechanism papers (1970s-1980s); Binnig-Rohrer STM (1982); Siegbahn ESCA (1967)',
   'institutional_markers':'Surface Science journal (Elsevier, 1964) FOUNDING MARKER; American Vacuum Society; Nobel Chemistry 2007 (Ertl); Nobel Physics 1981 (Siegbahn XPS), 1986 (Binnig-Rohrer STM)',
   'source_ids':'SRC_098','confidence':'A','evidence_type':'E4',
   'controversies':'Applicability of single-crystal model surface results to industrial supported catalysts (Somorjai pressure gap, materials gap); STM initially doubted; surface vs bulk distinction blurred at nanoscale',
   'pioneer_ids':'PION_239, PION_228, PION_229, PION_246',
   'enabling_breakthrough_ids':'BRKTH_083, BRKTH_076, BRKTH_067',
   'transforming_breakthrough_ids':'BRKTH_109, BRKTH_099',
   'critical_works':'Ertl reactions at surfaces papers (Science, Angewandte Chemie); Somorjai Chemistry in Two Dimensions (1981)',
   'critical_instruments':'Ultra-high vacuum chamber; LEED (Low Energy Electron Diffraction); STM; AFM; XPS (ESCA); Auger electron spectrometer'},

  {'node_id':'T3_CON_006','label':'Nanotechnology','type':'field','trunk_id':'3',
   'parent_candidate':'T3_CON_002, T3_CON_005, T3_MOD_001, T3_CON_003',
   'date_start':'1981','date_end':'2025','date_precision':'decade',
   'creation_event_type':'institutionalized_field','region':'Global',
   'description':'Science, engineering, and technology at 1-100 nm scale — where quantum effects, surface chemistry, and classical mechanics all simultaneously matter. Not a single discipline but a scale. STM (1981) enabled; fullerenes (1985), CNTs (1991), graphene (2004) as landmark materials. National Nanotechnology Initiative (NNI, 2000) institutionalized. ACTIVE field — still rapidly developing.',
   'core_idea':'At nanoscale (1-100 nm), materials exhibit size-dependent properties differing from bulk; surface-to-volume ratio determines behavior; quantum confinement effects become significant; nanoscale structures are both building blocks and functional devices.',
   'pioneers':'Gerd Binnig, Heinrich Rohrer, Richard Smalley, Robert Curl, Harold Kroto, Sumio Iijima, Don Eigler, Andre Geim, Konstantin Novoselov',
   'representative_works':'Feynman There\'s Plenty of Room at the Bottom (1959 lecture); Binnig-Rohrer STM (1982); Kroto et al. C60 (1985); Iijima CNTs (1991); Geim-Novoselov graphene (2004)',
   'institutional_markers':'Nanotechnology journal (IOP, 1990); NNI USA (2000) $500M/year; Nano Letters (ACS, 2001); NSECs (NSF, 2001); Nobel: C60 1996, STM 1986, graphene 2010; EU Graphene Flagship (2013, €1B)',
   'source_ids':'SRC_095, SRC_096','confidence':'A','evidence_type':'E4',
   'controversies':'Drexler molecular assembler concept vs Smalley objections; NNI hype cycle; health risks of engineered nanoparticles; definition of "nanotechnology" contested; military applications',
   'pioneer_ids':'PION_228, PION_229, PION_230, PION_231, PION_232, PION_233, PION_234',
   'enabling_breakthrough_ids':'BRKTH_109, BRKTH_110, BRKTH_096',
   'transforming_breakthrough_ids':'BRKTH_099, BRKTH_104',
   'critical_works':'Feynman lecture (1959); Drexler Engines of Creation (1986); Ratner Nanotechnology: A Gentle Introduction (2003)',
   'critical_instruments':'STM; AFM; electron microscope (HRTEM); atomic layer deposition; electron beam lithography'},

  {'node_id':'T3_CON_007','label':'Semiconductor Physics and Microelectronics','type':'field','trunk_id':'3',
   'parent_candidate':'T3_CON_002, T3_CON_003',
   'date_start':'1947','date_end':'2025','date_precision':'year',
   'creation_event_type':'institutionalized_field','region':'Global',
   'description':'Application of solid state physics to semiconductor devices. Transistor (1947) → integrated circuit (1958-1959) → Moore\'s Law scaling → modern computing. Core physics: band theory, p-n junctions, carrier dynamics, quantum tunneling at sub-5nm nodes. Bridges physics, materials science, electrical engineering.',
   'core_idea':'Semiconductor band structure determines electronic properties; p-n junctions enable charge carrier control; transistor switches/amplifies via majority carrier modulation; miniaturization follows Moore\'s Law with quantum effects dominating below ~5nm.',
   'pioneers':'John Bardeen, Walter Brattain, William Shockley, Jack Kilby, Robert Noyce, Gordon Moore, Herbert Kroemer, Zhores Alferov',
   'representative_works':'Bardeen-Brattain transistor (1947); Shockley Electrons and Holes in Semiconductors (1950); Kilby IC (1958); Kroemer heterostructure laser (1963)',
   'institutional_markers':'Transistor 1947 (Bell Labs) FOUNDING EVENT; Nobel Physics 1956 (Bardeen-Brattain-Shockley), 2000 (Kilby, Kroemer, Alferov); IEEE Transactions on Electron Devices (1952); Semiconductor Industry Association (1977); ITRS/IRDS roadmaps',
   'source_ids':'SRC_093, SRC_094','confidence':'A','evidence_type':'E4',
   'controversies':'Shockley credit-taking from Bardeen-Brattain; Silicon Valley spawned by Shockley\'s behavior (traitorous eight); Moore\'s Law as self-fulfilling prophecy vs physical law; EUV lithography feasibility debates 2000s-2010s',
   'pioneer_ids':'PION_208, PION_209, PION_226, PION_227',
   'enabling_breakthrough_ids':'BRKTH_076, BRKTH_096, BRKTH_088',
   'transforming_breakthrough_ids':'BRKTH_111, BRKTH_114',
   'critical_works':'Shockley Electrons and Holes in Semiconductors (1950); Sze Physics of Semiconductor Devices (1969); Mead and Conway VLSI Systems (1980)',
   'critical_instruments':'Photolithography; molecular beam epitaxy (MBE); ion implantation; atomic layer deposition; EUV scanner'},

  {'node_id':'T3_CON_008','label':'Polymer Science and Soft Matter Physics','type':'field','trunk_id':'3',
   'parent_candidate':'T3_MOD_001, T3_MOD_004, T3_CON_002',
   'date_start':'1920','date_end':'2025','date_precision':'decade',
   'creation_event_type':'named_field','region':'European',
   'description':'Study of macromolecules (polymers, colloids, liquid crystals, gels, biological soft matter) and their physical properties. Straddles organic chemistry, physical chemistry, and condensed matter physics. Nobel: Staudinger 1953 (macromolecules), Ziegler-Natta 1963 (polymerization), Flory 1974 (polymer theory), de Gennes 1991 (soft matter).',
   'core_idea':'Long chain molecules have unique statistical mechanical properties (random coil, reptation); polymer physical properties determined by chain statistics; soft matter systems share slow dynamics, sensitivity to entropy, and mesoscale structure.',
   'pioneers':'Hermann Staudinger, Paul Flory, Pierre-Gilles de Gennes, Karl Ziegler, Giulio Natta, Wallace Carothers',
   'representative_works':'Staudinger macromolecule concept (1920s); Flory Statistical Mechanics of Chain Molecules (1969); de Gennes Scaling Concepts in Polymer Physics (1979)',
   'institutional_markers':'Journal of Polymer Science (1946); ACS Polymer Division (1950s); Nobel: Staudinger 1953, Ziegler-Natta 1963, Flory 1974, de Gennes 1991',
   'source_ids':'SRC_094','confidence':'A','evidence_type':'E4',
   'controversies':'Staudinger macromolecule concept initially rejected by Wieland and other chemists (1920s-1930s); reptation model (de Gennes 1979) vs constraint release models; polymer melts chain statistics debate (Flory vs de Gennes)',
   'pioneer_ids':'PION_224, PION_225, PION_195',
   'enabling_breakthrough_ids':'BRKTH_076, BRKTH_092, BRKTH_065',
   'transforming_breakthrough_ids':'BRKTH_108, BRKTH_099',
   'critical_works':'Flory Principles of Polymer Chemistry (1953); de Gennes Scaling Concepts in Polymer Physics (1979); Edwards The Theory of Polymer Dynamics (1986)',
   'critical_instruments':'GPC (gel permeation chromatography); NMR (polymer structure); light scattering; rheometer; DSC (differential scanning calorimeter)'},

  {'node_id':'T3_CON_009','label':'Biochemistry and Structural Biology (Physical Methods)','type':'field','trunk_id':'3',
   'parent_candidate':'T3_MOD_004, T3_CON_004',
   'date_start':'1950','date_end':'2025','date_precision':'decade',
   'creation_event_type':'institutionalized_field','region':'Global',
   'description':'Chemistry and physics of living systems — primarily in Trunk 5 (Biology), but deeply connected to Trunk 3 via physical methods: X-ray crystallography (DNA 1953, proteins 1957-1960), NMR spectroscopy, cryo-electron microscopy, and computational molecular dynamics. Trunk 3 claims the physical/chemical methods contribution.',
   'core_idea':'Structure of biological macromolecules (proteins, nucleic acids) determines function; physical methods (X-ray, NMR, cryo-EM) reveal structure at atomic level; computational MD simulates dynamics; Trunk 3 physical chemistry tools revolutionized biology.',
   'pioneers':'Max Perutz, John Kendrew, Martin Karplus, Michael Levitt, Kurt Wüthrich, Joachim Frank',
   'representative_works':'Watson-Crick DNA structure (1953, Franklin X-ray data); Kendrew myoglobin (1958); Perutz hemoglobin (1960); Karplus MD simulation (1977)',
   'institutional_markers':'MRC Laboratory of Molecular Biology (Cambridge, 1962); Nobel: Perutz-Kendrew 1962, Sanger 1958+1980, Wüthrich 2002, Frank 2017; PDB (Protein Data Bank, 1971)',
   'source_ids':'SRC_098','confidence':'B','evidence_type':'E4',
   'controversies':'Rosalind Franklin credit for DNA X-ray data (Photo 51) not acknowledged in Nobel (Watson-Crick-Wilkins 1962); Trunk 3 vs Trunk 5 node ownership; cryo-EM resolution revolution obsoleting crystallography in some areas',
   'pioneer_ids':'PION_249, PION_250, PION_195',
   'enabling_breakthrough_ids':'BRKTH_088, BRKTH_108, BRKTH_099',
   'transforming_breakthrough_ids':'BRKTH_112, BRKTH_113',
   'critical_works':'Perutz and Kendrew protein structure papers (1958-1960); Karplus MD paper (1977); Frank cryo-EM Nobel lecture (2017)',
   'critical_instruments':'X-ray crystallography (synchrotron); NMR spectrometer (high-field); cryo-electron microscope; high-performance computers for MD'},

  {'node_id':'T3_CON_010','label':'2D Materials and Topological Quantum Materials','type':'subfield','trunk_id':'3',
   'parent_candidate':'T3_CON_002, T3_CON_006',
   'date_start':'2004','date_end':'2025','date_precision':'year',
   'creation_event_type':'modern_formulation','region':'Global',
   'description':'Two-dimensional materials (graphene, TMDs, van der Waals heterostructures) and topological quantum materials (topological insulators, Weyl semimetals, topological superconductors). Active/emerging frontier — Nobel Physics 2010 (graphene), 2016 (topological phases). Dedicated journal 2D Materials (IOP, 2014).',
   'core_idea':'2D materials have properties qualitatively different from bulk (Dirac fermions in graphene, valley polarization in TMDs); topological invariants classify quantum phases of matter; topology protects surface states against disorder; moiré superlattices engineer new quantum phases.',
   'pioneers':'Andre Geim, Konstantin Novoselov, David Thouless, Duncan Haldane, J. Michael Kosterlitz, Pablo Jarillo-Herrero',
   'representative_works':'Geim-Novoselov graphene (2004); TKNN invariant paper (1982); Haldane model (1988); magic-angle graphene (2018)',
   'institutional_markers':'Nobel Physics 2010 (Geim-Novoselov graphene), 2016 (Thouless-Haldane-Kosterlitz topological); 2D Materials journal (IOP, 2014); EU Graphene Flagship (2013, €1B)',
   'source_ids':'SRC_095, SRC_093','confidence':'A','evidence_type':'E4',
   'controversies':'Magic-angle graphene superconductivity mechanism (Mott insulator vs BCS-like); topological insulator material synthesis challenges; 2D semiconductor vs Si CMOS competition',
   'pioneer_ids':'PION_217, PION_218, PION_219, PION_220, PION_221',
   'enabling_breakthrough_ids':'BRKTH_109, BRKTH_103, BRKTH_110',
   'transforming_breakthrough_ids':'BRKTH_104',
   'critical_works':'Novoselov et al. Science (2004); TKNN Physical Review Letters (1982); Kane-Mele topological insulator (2005)',
   'critical_instruments':'STM; ARPES (Angle-Resolved Photoemission Spectroscopy); van der Waals heterostructure assembly; millikelvin dilution refrigerator'},

  {'node_id':'T3_CON_011','label':'Quantum Computing and Quantum Information','type':'field','trunk_id':'3',
   'parent_candidate':'T3_MOD_009, T3_CON_001, T3_CON_002',
   'date_start':'1980','date_end':'2025','date_precision':'decade',
   'creation_event_type':'named_field','region':'Global',
   'description':'Use of quantum superposition, entanglement, and interference for computation and communication. Feynman concept (1982); Shor algorithm (1994) established importance for cryptography; Google/IBM superconducting qubit hardware race; Preskill NISQ era (2018). EMERGING — no stable technology platform. Google Willow error correction milestone (2024).',
   'core_idea':'Quantum bits (qubits) exploit superposition and entanglement to enable exponential parallelism for certain problems; Shor algorithm threatens RSA; error correction below threshold enables scalable fault-tolerant computation; different physical platforms (superconducting, trapped ion, photonic) all viable.',
   'pioneers':'Peter Shor, David Wineland, John Preskill, Alain Aspect, John Clauser, Anton Zeilinger',
   'representative_works':'Shor algorithm (1994); Nielsen-Chuang textbook (2000); Preskill NISQ paper (2018); Google Willow (2024)',
   'institutional_markers':'Nielsen-Chuang textbook (2000); IBM Quantum Experience (2016, public cloud access); National Quantum Initiative Act (USA, 2018); Nobel Physics 2022 (Aspect-Clauser-Zeilinger entanglement); npj Quantum Information (2015); Quantum journal (2017)',
   'source_ids':'SRC_103, SRC_104','confidence':'A','evidence_type':'E4',
   'controversies':'Google "quantum supremacy" (2019) disputed by IBM; practical usefulness of NISQ era qubits uncertain; timelines for cryptographically relevant quantum computer highly uncertain (5-50 years); which hardware platform will win',
   'pioneer_ids':'PION_240, PION_241, PION_242, PION_243, PION_244, PION_245',
   'enabling_breakthrough_ids':'BRKTH_076, BRKTH_106, BRKTH_097',
   'transforming_breakthrough_ids':'BRKTH_105, BRKTH_116',
   'critical_works':'Shor algorithm (1994); Nielsen-Chuang (2000); Preskill NISQ (2018)',
   'critical_instruments':'Dilution refrigerator (mK temperatures); Josephson junction qubits; laser and trap systems; photon detectors'},

  {'node_id':'T3_CON_012','label':'Astrochemistry and Extreme-Conditions Chemistry','type':'field','trunk_id':'3',
   'parent_candidate':'T3_MOD_004, T3_MOD_007',
   'date_start':'1960','date_end':'2025','date_precision':'decade',
   'creation_event_type':'named_field','region':'Global',
   'description':'Chemistry under extreme conditions — interstellar space (ultra-low density, radiation, cryogenic temperatures) and high pressure (diamond anvil cell, megabar range). Two subfields: astrochemistry (molecular abundance in ISM, planetary atmospheres) and high-pressure chemistry (new phases, metallic hydrogen, room-temperature superconductors under pressure).',
   'core_idea':'Chemical species stable under extreme conditions differ fundamentally from those at ambient conditions; quantum chemistry predicts exotic species unobservable in normal laboratory; high pressure creates new phases with novel properties; interstellar medium chemistry is dominated by ion-molecule reactions and dust surface processes.',
   'pioneers':'William Klemperer, Ewine van Dishoeck, Neil Bartlett, Mohamed Eremets, Arthur Moulton',
   'representative_works':'Bartlett noble gas chemistry (1962); diamond anvil cell papers (1959+); van Dishoeck interstellar chemistry reviews',
   'institutional_markers':'Icarus journal (astrochemistry, 1962); IAU astrochemistry working groups; diamond anvil cell technology (1960s); Nobel: Bartlett-related discovery (no direct Nobel but noble gas compounds landmark)',
   'source_ids':'SRC_097','confidence':'B','evidence_type':'E3',
   'controversies':'Room-temperature superconductivity under pressure claims (many disputed); high-pressure hydrogen metallization timeline; interstellar molecular abundances calculation accuracy; astrochemistry vs cosmochemistry boundary',
   'pioneer_ids':'PION_239, PION_235, PION_238',
   'enabling_breakthrough_ids':'BRKTH_076, BRKTH_080, BRKTH_099',
   'transforming_breakthrough_ids':'BRKTH_108, BRKTH_102',
   'critical_works':'van Dishoeck Interstellar Chemistry Special Issue (2006); Mao-Bell diamond anvil cell review; Journal of Chemical Physics extreme conditions papers',
   'critical_instruments':'Diamond anvil cell; radio telescope (molecular line emission); Hubble/JWST spectrograph; high-pressure apparatus'},
]

print("Running Part 5: Field Nodes (MOD + CON)")
append_rows('nodes.csv', NODE_FIELDS, nodes)
print(f"Part 5 complete. {len(nodes)} nodes added (T3_MOD_001-011, T3_CON_001-012).")
