#!/usr/bin/env python3
"""
Part 3: Add modern breakthroughs (BRKTH_065-BRKTH_094).
Run from project root: python3 05_validation/add_trunk3_part3_mod_breakthroughs.py
"""
import csv, json, os

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '04_nodes_edges')

def append_rows(fname, fieldnames, rows):
    path = os.path.join(BASE, fname)
    with open(path, 'a', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
        for r in rows:
            w.writerow(r)
    print(f"  + {fname}: {len(rows)} rows added")

def J(lst): return json.dumps(lst, ensure_ascii=False)

BRKTH_FIELDS = ['breakthrough_id','name','type','date_or_range','date_precision',
                'pioneers_involved','description','enabling_factors','fields_enabled',
                'fields_transformed','representative_publication_json','cascading_impact',
                'source_ids','confidence','evidence_type']

mod_breakthroughs = [
  # ── CONCEPTUAL BREAKTHROUGHS ───────────────────────────────────────────────
  {'breakthrough_id':'BRKTH_065','name':'Law of Conservation of Energy','type':'concept',
   'date_or_range':'1840s','date_precision':'decade',
   'pioneers_involved':'James Prescott Joule, Julius Robert Mayer, Hermann von Helmholtz',
   'description':'Energy cannot be created or destroyed, only transformed from one form to another. Heat is a form of energy, not a substance. Joule established the mechanical equivalent of heat experimentally. Helmholtz formalized the principle mathematically (1847). Defeated caloric theory.',
   'enabling_factors':'Steam engine technology providing empirical heat-work relationships; Carnot cycle analysis; quantitative calorimetry',
   'fields_enabled':'T3_MOD_005','fields_transformed':'T3_MOD_005',
   'representative_publication_json':J([{"title":"Über die Erhaltung der Kraft","author":"Helmholtz, H.","date":"1847","note":"Mathematical formulation of energy conservation"}]),
   'cascading_impact':'Unified physics under energy concept; ended caloric theory; enabled all of thermodynamics; foundation for chemical thermodynamics and Gibbs free energy',
   'source_ids':'SRC_081','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_066','name':'Second Law of Thermodynamics and Entropy','type':'concept',
   'date_or_range':'1850-1865','date_precision':'decade',
   'pioneers_involved':'Rudolf Clausius, William Thomson (Lord Kelvin)',
   'description':'Heat flows spontaneously only from hot to cold (Kelvin-Planck and Clausius formulations, 1850-1851). Entropy S introduced by Clausius (1865): entropy of an isolated system always increases. Established thermodynamic arrow of time and limits of heat engine efficiency.',
   'enabling_factors':'Carnot cycle analysis; steam engine performance data; First Law (BRKTH_065) as prerequisite',
   'fields_enabled':'T3_MOD_005','fields_transformed':'T3_MOD_005',
   'representative_publication_json':J([{"title":"Über die bewegende Kraft der Wärme","author":"Clausius, R.","date":"1850","note":"Second law formulation"},{"title":"Über verschiedene für die Anwendung bequeme Formen der Hauptgleichungen","author":"Clausius, R.","date":"1865","note":"Entropy concept introduced"}]),
   'cascading_impact':'Limits of efficiency fundamental; entropy concept extends to information theory; statistical interpretation (BRKTH_069) followed; heat death of universe concept',
   'source_ids':'SRC_081','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_067','name':'Maxwell\'s Electromagnetic Theory','type':'formalization',
   'date_or_range':'1864-1873','date_precision':'decade',
   'pioneers_involved':'James Clerk Maxwell',
   'description':'Four equations (in modern form) unifying electricity, magnetism, and light. Predicted electromagnetic waves traveling at speed c. Demonstrated light is an electromagnetic wave. Displaced action-at-a-distance theories with field theory. Published 1864 paper and 1873 Treatise.',
   'enabling_factors':'Faraday\'s field lines concept; Ampere and Oersted electromagnetic discoveries; mathematical physics tradition',
   'fields_enabled':'T3_MOD_006','fields_transformed':'T3_EMD_008',
   'representative_publication_json':J([{"title":"A Dynamical Theory of the Electromagnetic Field","author":"Maxwell, J.C.","date":"1864","note":"Original Maxwell's equations paper"},{"title":"A Treatise on Electricity and Magnetism","author":"Maxwell, J.C.","date":"1873","note":"Comprehensive treatment"}]),
   'cascading_impact':'Radio technology (Hertz 1887); special relativity required constant c; quantum electrodynamics built on classical EM; entire electromagnetic technology civilization',
   'source_ids':'SRC_083','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_068','name':'Periodic Table of Elements','type':'concept',
   'date_or_range':'1869','date_precision':'year',
   'pioneers_involved':'Dmitri Mendeleev, Lothar Meyer',
   'description':'Mendeleev arranged 63 known elements by atomic weight; periodic recurrence of properties. Predicted three missing elements (eka-boron=Sc, eka-aluminium=Ga, eka-silicon=Ge) with their properties. Independent proposal by Lothar Meyer (1868, published 1870). Discovered elements filled gaps exactly as predicted.',
   'enabling_factors':'Atomic weight determinations (Cannizzaro 1858); large number of elements isolated; systematic chemical property data',
   'fields_enabled':'T3_MOD_003','fields_transformed':'T3_EMD_006',
   'representative_publication_json':J([{"title":"The Relation Between the Properties and Atomic Weights of the Elements","author":"Mendeleev, D.","date":"1869","note":"First periodic table publication"}]),
   'cascading_impact':'Organized all chemistry; predictive power confirmed theory; hinted at atomic structure (later quantum mechanics explains periodicity exactly); foundation of inorganic chemistry',
   'source_ids':'SRC_076','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_069','name':'Statistical Interpretation of Entropy','type':'concept',
   'date_or_range':'1872-1902','date_precision':'decade',
   'pioneers_involved':'Ludwig Boltzmann, James Clerk Maxwell, J. Willard Gibbs',
   'description':'Boltzmann: entropy S = k log W (microstate count W); thermodynamics derives from statistical behavior of atoms. Second law is statistical, not absolute — entropy decrease is improbable, not impossible. H-theorem (1872). Gibbs ensemble theory (1902) systematized statistical mechanics.',
   'enabling_factors':'Kinetic theory of gases (Maxwell velocity distribution, 1859); acceptance of atomic theory; probability theory',
   'fields_enabled':'T3_MOD_011','fields_transformed':'T3_MOD_005',
   'representative_publication_json':J([{"title":"Vorlesungen über Gastheorie","author":"Boltzmann, L.","date":"1896-1898","note":"Statistical mechanics of gases"},{"title":"Elementary Principles in Statistical Mechanics","author":"Gibbs, J.W.","date":"1902","note":"Ensemble theory systematization"}]),
   'cascading_impact':'Connected microscopic atomic world to macroscopic thermodynamics; Boltzmann constant fundamental; entropy-information connection (Shannon 1948); quantum statistical mechanics built on this',
   'source_ids':'SRC_081, SRC_082','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_070','name':'Energy Quantization (Planck\'s Quantum Hypothesis)','type':'concept',
   'date_or_range':'1900','date_precision':'year',
   'pioneers_involved':'Max Planck',
   'description':'Planck solved the ultraviolet catastrophe in blackbody radiation by hypothesizing energy exchanged in discrete quanta E = nhν. Planck\'s constant h introduced as fundamental constant. Revolutionary assumption made to fit experimental data, not from first principles — "an act of desperation" (Planck).',
   'enabling_factors':'Stefan-Boltzmann law; Wien\'s displacement law; Rayleigh-Jeans failure at short wavelengths; precise blackbody measurements',
   'fields_enabled':'T3_MOD_009','fields_transformed':'T3_MOD_006',
   'representative_publication_json':J([{"title":"Über eine Verbesserung der Wienschen Spektralgleichung","author":"Planck, M.","date":"1900","note":"First presentation of quantum hypothesis, October 1900"}]),
   'cascading_impact':'Initiated quantum revolution; Planck constant fundamental to all of quantum mechanics; Einstein photoelectric effect (1905); de Broglie wavelength; Heisenberg uncertainty principle',
   'source_ids':'SRC_078','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_071','name':'Special Relativity','type':'concept',
   'date_or_range':'1905','date_precision':'year',
   'pioneers_involved':'Albert Einstein, Hendrik Lorentz, Henri Poincaré',
   'description':'Einstein: space and time are relative; speed of light c is constant for all observers; simultaneity is relative; E=mc² (mass-energy equivalence). Length contraction and time dilation. No absolute frame of reference. Lorentz transformations (derived independently by Einstein from physical reasoning).',
   'enabling_factors':'Michelson-Morley null result (no ether); Maxwell\'s EM theory requiring constant c; Lorentz transformations (mathematical precursor)',
   'fields_enabled':'T3_MOD_010','fields_transformed':'T3_EMD_003',
   'representative_publication_json':J([{"title":"Zur Elektrodynamik bewegter Körper","author":"Einstein, A.","date":"1905","note":"Special relativity paper"},{"title":"Ist die Trägheit eines Körpers von seinem Energieinhalt abhängig?","author":"Einstein, A.","date":"1905","note":"E=mc² paper"}]),
   'cascading_impact':'Mass-energy equivalence (nuclear energy, nuclear weapons); GPS requires relativistic correction; particle physics requires relativistic quantum mechanics; led directly to general relativity',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_072','name':'Nuclear Atomic Model','type':'discovery',
   'date_or_range':'1911','date_precision':'year',
   'pioneers_involved':'Ernest Rutherford, Hans Geiger, Ernest Marsden',
   'description':'Rutherford\'s alpha-scattering experiment (Geiger-Marsden): alpha particles fired at gold foil showed large-angle backscattering. Concluded atom has tiny dense positively-charged nucleus (size ~10^-14 m) with electrons orbiting at distance; most of atom is empty space. Overturned Thomson\'s plum pudding model.',
   'enabling_factors':'Radioactivity (alpha particles as probe, BRKTH_082); cathode ray tube (BRKTH_081); Thomson\'s electron discovery',
   'fields_enabled':'T3_MOD_008','fields_transformed':'T3_MOD_008',
   'representative_publication_json':J([{"title":"The Scattering of α and β Particles by Matter and the Structure of the Atom","author":"Rutherford, E.","date":"1911","note":"Nuclear atom model paper"}]),
   'cascading_impact':'Nuclear physics field opened; Bohr model (1913) built directly on nuclear atom; quantum mechanics required to explain atomic stability; nuclear reactions and reactors',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_073','name':'Bohr Atomic Model','type':'concept',
   'date_or_range':'1913','date_precision':'year',
   'pioneers_involved':'Niels Bohr',
   'description':'Electrons occupy quantized stable orbits (n=1,2,3...); energy levels discrete (E = -13.6/n² eV for hydrogen); transitions between levels emit/absorb photons at specific frequencies. Explained hydrogen spectrum exactly. Old Quantum Theory peak — ad hoc quantization rules, later replaced by full quantum mechanics.',
   'enabling_factors':'Nuclear atom model (BRKTH_072); energy quantization (BRKTH_070); hydrogen spectral series (Balmer, Lyman, Paschen)',
   'fields_enabled':'T3_MOD_009','fields_transformed':'T3_MOD_008',
   'representative_publication_json':J([{"title":"On the Constitution of Atoms and Molecules","author":"Bohr, N.","date":"1913","note":"Three-part paper establishing Bohr model, Philosophical Magazine"}]),
   'cascading_impact':'First quantitative explanation of atomic spectra; concept of energy levels foundational; motivated matrix mechanics (1925) and wave mechanics (1926); quantum numbers (n, l, m, s) emerged from this',
   'source_ids':'SRC_078','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_074','name':'General Relativity','type':'formalization',
   'date_or_range':'1915','date_precision':'year',
   'pioneers_involved':'Albert Einstein',
   'description':'Gravity is the curvature of spacetime caused by mass/energy. Einstein field equations Gμν = 8πGTμν/c⁴. Equivalence principle: gravity = acceleration locally. Explained Mercury\'s precessing perihelion (43 arcsec/century). Predicted light bending confirmed 1919. Predicted gravitational waves (confirmed 2015).',
   'enabling_factors':'Special relativity (BRKTH_071); Riemannian geometry; equivalence principle insight; Minkowski spacetime formalism',
   'fields_enabled':'T3_MOD_010','fields_transformed':'T3_MOD_010',
   'representative_publication_json':J([{"title":"Die Feldgleichungen der Gravitation","author":"Einstein, A.","date":"1915","note":"Field equations of general relativity"},{"title":"Die Grundlage der allgemeinen Relativitätstheorie","author":"Einstein, A.","date":"1916","note":"Comprehensive general relativity paper"}]),
   'cascading_impact':'Black hole prediction (confirmed); gravitational waves (LIGO 2015); Big Bang cosmology; GPS requires GR corrections; predicts expanding universe (Einstein initially resisted)',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_075','name':'Wave-Particle Duality','type':'concept',
   'date_or_range':'1905-1924','date_precision':'decade',
   'pioneers_involved':'Albert Einstein, Louis de Broglie',
   'description':'Einstein (1905): light has particle properties (photons, E=hν) explaining photoelectric effect. De Broglie (1924): matter has wave properties, wavelength λ=h/p. Both waves and particles are necessary descriptions. Complementarity principle later formalized by Bohr.',
   'enabling_factors':'Photoelectric effect data; energy quantization (BRKTH_070); Young\'s double slit (wave interference); Compton scattering (1923)',
   'fields_enabled':'T3_MOD_009','fields_transformed':'T3_MOD_006',
   'representative_publication_json':J([{"title":"Über einen die Erzeugung und Verwandlung des Lichtes betreffenden heuristischen Gesichtspunkt","author":"Einstein, A.","date":"1905","note":"Photoelectric effect, light quanta"},{"title":"Recherches sur la théorie des quanta (PhD thesis)","author":"de Broglie, L.","date":"1924","note":"Matter waves hypothesis"}]),
   'cascading_impact':'Electron diffraction confirmed de Broglie (Davisson-Germer 1927); wave mechanics (Schrödinger 1926) built on matter waves; electron microscope enabled; quantum mechanics requires both descriptions',
   'source_ids':'SRC_078','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_076','name':'Quantum Mechanics (Matrix and Wave Formulations)','type':'formalization',
   'date_or_range':'1925-1926','date_precision':'year',
   'pioneers_involved':'Werner Heisenberg, Max Born, Pascual Jordan, Erwin Schrödinger, Paul Dirac',
   'description':'Complete quantum mechanics established in two equivalent formulations. Matrix mechanics: Heisenberg, Born, Jordan (1925) — observables as matrices, non-commuting algebra. Wave mechanics: Schrödinger (1926) — Ψ satisfies wave equation, eigenvalue problem. Schrödinger proved equivalence. Born probabilistic interpretation of |Ψ|². Dirac unified framework (1930).',
   'enabling_factors':'Bohr atomic model (BRKTH_073); wave-particle duality (BRKTH_075); Planck constant; spectral data to be explained',
   'fields_enabled':'T3_MOD_009','fields_transformed':'T3_EMD_003',
   'representative_publication_json':J([{"title":"Über quantentheoretische Umdeutung kinematischer und mechanischer Beziehungen","author":"Heisenberg, W.","date":"1925","note":"Matrix mechanics birth paper"},{"title":"Quantisierung als Eigenwertproblem (I-IV)","author":"Schrödinger, E.","date":"1926","note":"Wave mechanics"}]),
   'cascading_impact':'Most successful physical theory in history; explains all chemistry (Dirac: all chemistry is just quantum mechanics); quantum electrodynamics; transistor; laser; entire modern chemistry',
   'source_ids':'SRC_078, SRC_079','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_077','name':'Heisenberg Uncertainty Principle','type':'concept',
   'date_or_range':'1927','date_precision':'year',
   'pioneers_involved':'Werner Heisenberg',
   'description':'Δx·Δp ≥ ħ/2 (position and momentum cannot both be known precisely simultaneously). ΔE·Δt ≥ ħ/2 (energy and time complementary). Not a measurement limitation but fundamental to quantum reality. Derived from non-commutativity of position and momentum operators in quantum mechanics.',
   'enabling_factors':'Matrix mechanics non-commuting observables (BRKTH_076); quantum mechanics framework',
   'fields_enabled':'T3_MOD_009','fields_transformed':'T3_MOD_009',
   'representative_publication_json':J([{"title":"Über den anschaulichen Inhalt der quantentheoretischen Kinematik und Mechanik","author":"Heisenberg, W.","date":"1927","note":"Uncertainty principle paper"}]),
   'cascading_impact':'Determinism abandoned in physics; zero-point energy (consequences for chemistry and low T physics); virtual particles (vacuum fluctuations); philosophical revolution about nature of reality',
   'source_ids':'SRC_078','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_078','name':'Pauli Exclusion Principle','type':'concept',
   'date_or_range':'1925','date_precision':'year',
   'pioneers_involved':'Wolfgang Pauli',
   'description':'No two identical fermions (spin-1/2 particles) can occupy the same quantum state simultaneously. Explained electron shell structure of atoms and periodic table. Matter stability explained (fermions resist compression). Spin statistics theorem (Pauli, 1940): fermions have half-integer spin, bosons integer spin.',
   'enabling_factors':'Spectroscopic anomalies (doublet splitting); quantum numbers; matrix mechanics',
   'fields_enabled':'T3_MOD_009','fields_transformed':'T3_MOD_008',
   'representative_publication_json':J([{"title":"Über den Zusammenhang des Abschlusses der Elektronengruppen im Atom mit der Komplexstruktur der Spektren","author":"Pauli, W.","date":"1925","note":"Exclusion principle paper"}]),
   'cascading_impact':'Explains periodic table (electron shell structure); matter stability; white dwarf and neutron star stability (degeneracy pressure); fermionic behavior fundamental to condensed matter physics',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_079','name':'Dirac Equation and Antimatter Prediction','type':'formalization',
   'date_or_range':'1928-1932','date_precision':'year',
   'pioneers_involved':'Paul Dirac, Carl Anderson',
   'description':'Dirac equation (1928): relativistic quantum mechanics for spin-1/2 particles; combines special relativity and quantum mechanics. Predicted negative energy solutions interpreted as antiparticles (1931). Anderson discovered positron (anti-electron) in cosmic rays (1932). First example of antimatter.',
   'enabling_factors':'Quantum mechanics (BRKTH_076); special relativity (BRKTH_071); Klein-Gordon equation (scalar relativistic QM)',
   'fields_enabled':'T3_CON_001','fields_transformed':'T3_MOD_009',
   'representative_publication_json':J([{"title":"The Quantum Theory of the Electron","author":"Dirac, P.A.M.","date":"1928","note":"Dirac equation papers, Proceedings Royal Society"},{"title":"The Positive Electron","author":"Anderson, C.D.","date":"1932","note":"Positron discovery paper"}]),
   'cascading_impact':'Quantum field theory foundations; antimatter physics; PET scan in medicine; Dirac sea/vacuum concept; relativistic quantum field theory (QED) required this framework',
   'source_ids':'SRC_079, SRC_080','confidence':'A','evidence_type':'E2'},

  # ── TECHNOLOGICAL/EXPERIMENTAL BREAKTHROUGHS ───────────────────────────────
  {'breakthrough_id':'BRKTH_080','name':'Emission Spectroscopy','type':'instrument',
   'date_or_range':'1859-1860','date_precision':'year',
   'pioneers_involved':'Gustav Kirchhoff, Robert Bunsen',
   'description':'Kirchhoff and Bunsen: each element produces unique spectral lines when heated (emission spectrum). Observation of Fraunhofer absorption lines in solar spectrum explained (1859). Bunsen burner provided clean flame for spectroscopy. New element helium discovered in sun before Earth (1868).',
   'enabling_factors':'Fraunhofer spectral line observations (1814); prism optics; Bunsen burner clean combustion',
   'fields_enabled':'T3_MOD_002','fields_transformed':'T3_EMD_007',
   'representative_publication_json':J([{"title":"Chemische Analyse durch Spectralbeobachtungen","author":"Kirchhoff, G. and Bunsen, R.","date":"1860","note":"Founding spectroscopic analysis paper"}]),
   'cascading_impact':'Analytical chemistry transformed; astronomical element discovery; quantum theory data (spectral lines explained by Bohr 1913); NMR and all modern spectroscopy descend from this',
   'source_ids':'SRC_076','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_081','name':'Electron Discovery (Cathode Ray Tube)','type':'discovery',
   'date_or_range':'1897','date_precision':'year',
   'pioneers_involved':'J.J. Thomson',
   'description':'Thomson demonstrated cathode rays are streams of particles (electrons) with charge and mass. Measured charge-to-mass ratio (e/m = 1.76×10¹¹ C/kg). First subatomic particle discovered; proved atoms are divisible. Proposed plum pudding atomic model (soon replaced by nuclear model).',
   'enabling_factors':'Vacuum tube technology; electric and magnetic field deflection apparatus; cathode ray tube development',
   'fields_enabled':'T3_MOD_008','fields_transformed':'T3_EMD_006',
   'representative_publication_json':J([{"title":"Cathode Rays","author":"Thomson, J.J.","date":"1897","note":"Electron discovery paper, Philosophical Magazine"}]),
   'cascading_impact':'Subatomic physics opened; atomic structure research; all subsequent atomic physics; electronics technology based on electron manipulation; quantum mechanics explains electron behavior',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_082','name':'Radioactivity Discovery','type':'discovery',
   'date_or_range':'1896-1898','date_precision':'year',
   'pioneers_involved':'Henri Becquerel, Marie Curie, Pierre Curie',
   'description':'Becquerel (1896): uranium emits penetrating radiation spontaneously. Marie and Pierre Curie isolated polonium and radium (1898); coined term "radioactivity." Alpha, beta, gamma rays distinguished by Rutherford. Natural transmutation of elements via radioactive decay.',
   'enabling_factors':'X-ray discovery (Röntgen 1895, BRKTH_083) prompted investigation of fluorescent materials; photographic plates',
   'fields_enabled':'T3_MOD_008','fields_transformed':'T3_MOD_008',
   'representative_publication_json':J([{"title":"Sur les radiations émises par phosphorescence","author":"Becquerel, H.","date":"1896","note":"Radioactivity discovery"},{"title":"Sur une nouvelle substance fortement radioactive","author":"Curie, M. and Curie, P.","date":"1898","note":"Radium discovery"}]),
   'cascading_impact':'Nuclear physics field opened; atomic transmutation; nuclear medicine (radium therapy); isotopes discovered; radiocarbon dating; nuclear reactors',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_083','name':'X-ray Discovery','type':'discovery',
   'date_or_range':'1895','date_precision':'year',
   'pioneers_involved':'Wilhelm Röntgen',
   'description':'Röntgen discovered penetrating radiation from cathode ray tube experiment that darkened photographic plates through cardboard and flesh. Named X-rays (unknown rays). First Nobel Prize in Physics (1901). Medical imaging application immediate — first X-ray image was of wife\'s hand.',
   'enabling_factors':'Cathode ray tube experiments; photographic plates',
   'fields_enabled':'T3_MOD_008','fields_transformed':'T3_EMD_007',
   'representative_publication_json':J([{"title":"Über eine neue Art von Strahlen","author":"Röntgen, W.C.","date":"1895","note":"X-ray discovery paper"}]),
   'cascading_impact':'Medical imaging revolutionized; X-ray crystallography (von Laue 1912, BRKTH_088) opened structural chemistry; electromagnetic spectrum extended; prompted radioactivity investigation',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_084','name':'Michelson Interferometer and Ether Null Result','type':'instrument',
   'date_or_range':'1881-1887','date_precision':'decade',
   'pioneers_involved':'Albert A. Michelson, Edward Morley',
   'description':'Michelson (1881, improved Michelson-Morley 1887): precision optical interferometer measuring light speed. Michelson-Morley experiment found null result — no ether wind detected. Light speed same in all directions. Precision measurement instrument (Nobel Physics 1907, first American Nobel in science).',
   'enabling_factors':'Precision optics; stable mechanical platform; wave theory of light',
   'fields_enabled':'T3_MOD_010','fields_transformed':'T3_EMD_007',
   'representative_publication_json':J([{"title":"On the Relative Motion of the Earth and the Luminiferous Ether","author":"Michelson, A.A. and Morley, E.W.","date":"1887","note":"Famous null result experiment"}]),
   'cascading_impact':'Ether concept demolished; paved way for special relativity; interferometry became precision measurement tool; modern LIGO gravitational wave detection uses advanced interferometry',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_085','name':'Cloud Chamber','type':'instrument',
   'date_or_range':'1911','date_precision':'year',
   'pioneers_involved':'Charles Thomson Rees Wilson',
   'description':'Wilson: supersaturated water vapor condenses on ions created by charged particle tracks. Charged particle paths made visible as trails of droplets. First device to visualize subatomic particle trajectories. Nobel Physics 1927. Cosmic ray studies and early particle physics relied on cloud chambers.',
   'enabling_factors':'Observation of cloud formation on ions; radioactivity knowledge; alpha particle probes',
   'fields_enabled':'T3_MOD_008','fields_transformed':'T3_MOD_008',
   'representative_publication_json':J([{"title":"On a Method of Making Visible the Paths of Ionising Particles through a Gas","author":"Wilson, C.T.R.","date":"1911","note":"Cloud chamber paper"}]),
   'cascading_impact':'Positron discovered (Anderson 1932); cosmic ray particles; muon discovered; particle physics experimental technique; later replaced by bubble chamber and wire chambers',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_086','name':'Alpha Scattering Experiment','type':'experimental_demonstration',
   'date_or_range':'1909-1911','date_precision':'year',
   'pioneers_involved':'Ernest Rutherford, Hans Geiger, Ernest Marsden',
   'description':'Geiger and Marsden (Rutherford\'s lab): alpha particles fired at gold foil. Most pass through but some scatter at large angles, including back-reflection. Rutherford concluded atoms have tiny, dense, positively-charged nuclei. Key experiment that established nuclear atom model.',
   'enabling_factors':'Alpha particle source (radioactivity, BRKTH_082); zinc sulfide scintillation screen; thin gold foil preparation',
   'fields_enabled':'T3_MOD_008','fields_transformed':'T3_MOD_008',
   'representative_publication_json':J([{"title":"The Scattering of α Particles by Matter","author":"Geiger, H. and Marsden, E.","date":"1909","note":"Initial scattering experiment"},{"title":"The Scattering of α and β Particles by Matter","author":"Rutherford, E.","date":"1911","note":"Nuclear model interpretation"}]),
   'cascading_impact':'Nuclear atom model (BRKTH_072) established from this experiment; Bohr model followed; all of nuclear physics; neutron discovery; nuclear reactions',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_087','name':'Mass Spectrometry','type':'instrument',
   'date_or_range':'1912-1920s','date_precision':'decade',
   'pioneers_involved':'J.J. Thomson, Francis William Aston',
   'description':'Thomson (1912): first mass spectrograph separating ions by m/e ratio. Aston (1919): mass spectrograph with higher precision. Discovered isotopes of neon (1919) and demonstrated mass defect. Aston Noble Chemistry 1922. Precise atomic mass measurements; isotope identification.',
   'enabling_factors':'Cathode ray tube technology; vacuum pumps; magnetic field ion deflection; Thomson\'s electron discovery',
   'fields_enabled':'T3_MOD_002','fields_transformed':'T3_MOD_008',
   'representative_publication_json':J([{"title":"Isotopes (monograph)","author":"Aston, F.W.","date":"1922","note":"Comprehensive isotope mass spectrometry"},{"title":"Neon","author":"Aston, F.W.","date":"1919","note":"Isotope discovery"}]),
   'cascading_impact':'Isotopes confirmed (Soddy theory validated); nuclear physics mass-energy calculations; analytical chemistry (GC-MS etc.); protein mass spectrometry (modern structural biology); nuclear binding energy',
   'source_ids':'SRC_076','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_088','name':'X-ray Crystallography','type':'instrument',
   'date_or_range':'1912-1920s','date_precision':'decade',
   'pioneers_involved':'Max von Laue, William Henry Bragg, William Lawrence Bragg',
   'description':'Von Laue (1912): X-rays diffracted by crystal lattice, proving both wave nature of X-rays and periodic crystal structure. Bragg and son (1913-1915): Bragg\'s law nλ = 2d sin θ; first crystal structures solved (NaCl, diamond). Nobel Physics 1914 (Laue), 1915 (Bragg × 2 — only father-son Nobel).',
   'enabling_factors':'X-ray discovery (BRKTH_083); crystal preparation; photographic detection',
   'fields_enabled':'T3_MOD_003','fields_transformed':'T3_MOD_002',
   'representative_publication_json':J([{"title":"Röntgenstrahl-Interferenzen","author":"Friedrich, W., Knipping, P. and Laue, M.","date":"1912","note":"X-ray diffraction discovery"},{"title":"X Rays and Crystal Structure","author":"Bragg, W.H. and Bragg, W.L.","date":"1915","note":"Crystal structure determination methods"}]),
   'cascading_impact':'Crystal structures of all materials determined; protein structure determination (hemoglobin 1959, DNA 1953); Trunk 5 biology revolution; pharmaceutical drug design; materials science',
   'source_ids':'SRC_079','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_089','name':'Cyclotron Particle Accelerator','type':'instrument',
   'date_or_range':'1930-1932','date_precision':'year',
   'pioneers_involved':'Ernest Orlando Lawrence',
   'description':'Lawrence (1930): cyclotron accelerates charged particles in spiral path using magnetic field and alternating electric field. First cyclotron (1930) 4 inches; scaled up. Enabled artificial nuclear reactions and element production. Nobel Physics 1939.',
   'enabling_factors':'Radiofrequency electronics; large electromagnets; vacuum technology; nuclear physics knowledge',
   'fields_enabled':'T3_MOD_008','fields_transformed':'T3_MOD_008',
   'representative_publication_json':J([{"title":"The Production of High Speed Light Ions Without the Use of High Voltages","author":"Lawrence, E.O. and Livingston, M.S.","date":"1932","note":"Cyclotron principle paper"}]),
   'cascading_impact':'Particle accelerators (synchrotron, LHC lineage); technetium first artificial element; nuclear medicine (PET, cancer treatment); neutron production for research; particle physics experiments',
   'source_ids':'SRC_080','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_090','name':'Precision Thermochemical Calorimetry','type':'instrument',
   'date_or_range':'1840-1920','date_precision':'century',
   'pioneers_involved':'James Prescott Joule, Julius Thomsen, Marcellin Berthelot',
   'description':'Development of precision calorimeters: bomb calorimeter (combustion heats), differential calorimeter, solution calorimetry. Joule\'s paddle wheel establishes mechanical equivalent of heat (1845). Hess\'s law (1840): heat of reaction path-independent. Thermochemistry as quantitative discipline.',
   'enabling_factors':'Mercury thermometers; precision balances; understanding of first law (BRKTH_065)',
   'fields_enabled':'T3_MOD_004','fields_transformed':'T3_MOD_005',
   'representative_publication_json':J([{"title":"On the Mechanical Equivalent of Heat","author":"Joule, J.P.","date":"1845","note":"Mechanical equivalent of heat"},{"title":"Thermochemie","author":"Thomsen, J.","date":"1882","note":"Systematic thermochemical measurements"}]),
   'cascading_impact':'Physical chemistry thermodynamics (Gibbs free energy calculation); industrial chemistry process design; reaction safety assessment; calorimetry in materials science (DSC)',
   'source_ids':'SRC_081','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_091','name':'Electrochemical Methods (Galvanic Cells and Electrolysis)','type':'instrument',
   'date_or_range':'1800-1920','date_precision':'century',
   'pioneers_involved':'Humphry Davy, Michael Faraday, Heyrovsky, Walther Nernst',
   'description':'Faraday\'s laws of electrolysis (1833-1834); galvanic cells quantified; reference electrodes standardized; polarography (Heyrovsky, 1922, Nobel Chemistry 1959). Nernst equation relating electrode potential to concentration. pH measurement standardized. Electroanalytical chemistry established.',
   'enabling_factors':'Voltaic pile (BRKTH_064, existing breakthrough); Faraday\'s electromagnetic work; Arrhenius ionic dissociation theory',
   'fields_enabled':'T3_MOD_004','fields_transformed':'T3_MOD_004',
   'representative_publication_json':J([{"title":"Experimental Researches in Electricity","author":"Faraday, M.","date":"1833","note":"Faraday's electrolysis laws"},{"title":"Researches on the Polarization of Electrodes","author":"Heyrovsky, J.","date":"1922","note":"Polarography invention"}]),
   'cascading_impact':'Analytical chemistry (potentiometry, amperometry); electrochemical synthesis; batteries and fuel cells; corrosion science; biochemical electrochemistry',
   'source_ids':'SRC_075','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_092','name':'Organic Synthesis Methods (Named Reactions Arsenal)','type':'method',
   'date_or_range':'1850-1940','date_precision':'century',
   'pioneers_involved':'Victor Grignard, Otto Diels, Kurt Alder, Emil Fischer, Adolf von Baeyer',
   'description':'Development of key synthetic methods: Grignard reagent (1900, Nobel 1912); Diels-Alder cycloaddition (1928, Nobel 1950); Reformatsky reaction; Claisen condensation; Wittig reaction; Fischer esterification; Baeyer strain theory. Built systematic toolkit for organic synthesis.',
   'enabling_factors':'Structural theory (Kekulé, BRKTH_068 predecessor); organic analysis techniques; laboratory infrastructure',
   'fields_enabled':'T3_MOD_001','fields_transformed':'T3_MOD_001',
   'representative_publication_json':J([{"title":"Sur quelques propriétés nouvelles des combinaisons organo-magnésiennes mixtes","author":"Grignard, V.","date":"1900","note":"Grignard reagent"},{"title":"Synthesen in der hydroaromatischen Reihe","author":"Diels, O. and Alder, K.","date":"1928","note":"Diels-Alder reaction"}]),
   'cascading_impact':'Complex molecule synthesis; pharmaceutical synthesis (aspirin, antibiotics, steroids); dye industry; modern total synthesis enables any target molecule; polymer chemistry',
   'source_ids':'SRC_076','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_093','name':'Chromatographic Separation Methods','type':'method',
   'date_or_range':'1900-1940','date_precision':'decade',
   'pioneers_involved':'Mikhail Tswett, Richard Martin, Richard Laurence Millington Synge',
   'description':'Tswett (1900s): column chromatography separating plant pigments by differential adsorption. Martin and Synge (1941): partition chromatography theory; Nobel Chemistry 1952. Led to paper chromatography, thin-layer chromatography, gas chromatography (1950s), HPLC (1960s). Universal separation/purification method.',
   'enabling_factors':'Adsorption chemistry knowledge; organic chemistry need for pure compounds; Tswett\'s systematic approach',
   'fields_enabled':'T3_MOD_002','fields_transformed':'T3_MOD_001',
   'representative_publication_json':J([{"title":"Die Adsorptionsanalyse und die chromatographische Methode","author":"Tswett, M.","date":"1906","note":"First chromatography publication"},{"title":"A New Form of Chromatogram Employing Two Liquid Phases","author":"Martin, A.J.P. and Synge, R.L.M.","date":"1941","note":"Partition chromatography theory"}]),
   'cascading_impact':'Analytical chemistry revolutionized; biochemistry (amino acid sequencing by paper chromatography); environmental monitoring (GC-MS pesticides); pharmaceutical quality control; proteomics (LC-MS)',
   'source_ids':'SRC_076','confidence':'A','evidence_type':'E2'},

  {'breakthrough_id':'BRKTH_094','name':'Nuclear Fission and First Controlled Chain Reaction','type':'experimental_demonstration',
   'date_or_range':'1938-1942','date_precision':'year',
   'pioneers_involved':'Otto Hahn, Lise Meitner, Enrico Fermi',
   'description':'Hahn and Strassmann (1938): bombarding uranium with neutrons produces barium — nuclear fission. Meitner and Frisch (1939): theoretical interpretation using mass-energy equivalence; coined "fission." Fermi (December 2, 1942): first controlled nuclear chain reaction (Chicago Pile-1). Manhattan Project application.',
   'enabling_factors':'Neutron discovery (Chadwick 1932); cyclotron (BRKTH_089); quantum mechanics nuclear theory; mass-energy equivalence (BRKTH_071)',
   'fields_enabled':'T3_MOD_008','fields_transformed':'T3_MOD_008',
   'representative_publication_json':J([{"title":"Über den Nachweis und das Verhalten der bei der Bestrahlung des Urans","author":"Hahn, O. and Strassmann, F.","date":"1939","note":"Fission discovery paper"},{"title":"Disintegration of Uranium by Neutrons","author":"Meitner, L. and Frisch, O.R.","date":"1939","note":"Fission theoretical interpretation"}]),
   'cascading_impact':'Nuclear age; nuclear weapons (Manhattan Project); nuclear power; radiation therapy; radionuclide production; neutron scattering tools for materials science',
   'source_ids':'SRC_079, SRC_080','confidence':'A','evidence_type':'E2'},
]

print("Running Part 3: Modern Breakthroughs")
append_rows('breakthroughs.csv', BRKTH_FIELDS, mod_breakthroughs)
print(f"Part 3 complete. {len(mod_breakthroughs)} modern breakthroughs added (BRKTH_065-BRKTH_094).")
